import { publicProgressionPlayer } from "../../platform/progression.js";
import { randomBytes } from "node:crypto";
import type { Server, Socket } from "socket.io";
import type { HalieusLiveRoomSummary } from "../../../../shared/platform/live-games.js";
import type { ConnectFourActionLogEntry, ConnectFourAiDifficulty, ConnectFourBestOf, ConnectFourDisc, ConnectFourMatchMode, ConnectFourPublicPlayer, ConnectFourPublicState, ConnectFourRoundResult } from "../../../../shared/games/connect-four/types.js";
import { finalizeSession, recordWorkingSession } from "../../platform/sessionArchive.js";

interface Player extends ConnectFourPublicPlayer { reconnectToken: string; }
interface Room {
  code:string; createdAt:number; startedAt:number|null; updatedAt:number;
  phase:"lobby"|"playing"|"round-over"|"finished"; matchMode:ConnectFourMatchMode;
  bestOf:ConnectFourBestOf; targetWins:number; roundNumber:number; roundHistory:ConnectFourRoundResult[];
  players:Player[]; spectators:Map<string,string>; board:ConnectFourDisc[];
  currentTurnPlayerId:string|null; winnerPlayerId:string|null; roundWinnerPlayerId:string|null; draw:boolean;
  turnNumber:number; lastDropIndex:number|null; status:string; actionSequence:number; actionLog:ConnectFourActionLogEntry[];
}
const rooms = new Map<string, Room>();
const aiTimers = new Map<string, NodeJS.Timeout>();
const AI_NAMES = ["Nova","Rook","Echo","Mira","Juno","Sol","Vale","Orion"];
function token(){ return randomBytes(8).toString("base64url").slice(0,10).toUpperCase(); }
function code(v:unknown){ return typeof v === "string" ? v.trim().toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6) : ""; }
function name(v:unknown){ return typeof v === "string" ? v.trim().slice(0,24) : ""; }
function mode(v:unknown):ConnectFourMatchMode{ return v === "ranked" ? "ranked" : "casual"; }
function bestOf(v:unknown):ConnectFourBestOf { const n=Number(v); return n===3||n===5?n:1; }
function difficulty(v:unknown):ConnectFourAiDifficulty{ return v === "easy" || v === "hard" ? v : "normal"; }
function pub(p:Player):ConnectFourPublicPlayer{ const { reconnectToken:_r, ...rest } = p; return publicProgressionPlayer(rest); }
function publicState(room:Room, viewerId:string|null, isSpectator:boolean):ConnectFourPublicState { return { code:room.code, createdAt:room.createdAt, startedAt:room.startedAt, updatedAt:room.updatedAt, phase:room.phase, matchMode:room.matchMode, bestOf:room.bestOf, targetWins:room.targetWins, roundNumber:room.roundNumber, roundHistory:[...room.roundHistory], players:room.players.map(pub), spectatorCount:room.spectators.size, viewerPlayerId:viewerId, isSpectator, board:[...room.board], currentTurnPlayerId:room.currentTurnPlayerId, winnerPlayerId:room.winnerPlayerId, roundWinnerPlayerId:room.roundWinnerPlayerId, draw:room.draw, turnNumber:room.turnNumber, lastDropIndex:room.lastDropIndex, status:room.status, actionLog:room.actionLog.slice(-160) }; }
function log(room:Room, entry:Omit<ConnectFourActionLogEntry,"sequence"|"at">){ room.actionSequence++; room.actionLog.push({ ...entry, sequence:room.actionSequence, at:Date.now() }); if(room.actionLog.length>160) room.actionLog.splice(0,room.actionLog.length-160); }
function archive(room:Room){ return { ...room, spectators:[...room.spectators.entries()] }; }
function emit(io:Server, room:Room){ room.updatedAt=Date.now(); recordWorkingSession("connect-four",room.code,room.createdAt,archive(room)); for(const p of room.players) if(!p.isAi&&p.isConnected) io.to(p.id).emit("connect-four:state",publicState(room,p.id,false)); for(const id of room.spectators.keys()) io.to(id).emit("connect-four:state",publicState(room,null,true)); scheduleAi(io,room); }
function idx(r:number,c:number){ return r*7+c; }
function winning(board:ConnectFourDisc[], disc:ConnectFourDisc){ for(let r=0;r<6;r++)for(let c=0;c<7;c++){ const dirs=[[0,1],[1,0],[1,1],[1,-1]]; for(const [dr,dc] of dirs){ let ok=true; for(let k=0;k<4;k++){ const rr=r+dr*k, cc=c+dc*k; if(rr<0||rr>=6||cc<0||cc>=7||board[idx(rr,cc)]!==disc){ok=false;break;} } if(ok)return true; } } return false; }
function dropIndex(board:ConnectFourDisc[], column:number){ if(column<0||column>6)return -1; for(let r=5;r>=0;r--) if(board[idx(r,column)]===0)return idx(r,column); return -1; }
function legalColumns(board:ConnectFourDisc[]){ return Array.from({length:7},(_,c)=>c).filter(c=>dropIndex(board,c)>=0); }
function other(room:Room,p:Player){ return room.players.find(x=>x.id!==p.id)??null; }
function finaliseMatch(io:Server, room:Room, winner:Player|null, reason?:string, archiveStatus: "completed" | "host-ended" = "completed"){ room.phase="finished"; room.currentTurnPlayerId=null; room.winnerPlayerId=winner?.id??null; room.status=reason ?? (winner?`${winner.name} wins the Connect Four series ${winner.seriesWins}-${other(room,winner)?.seriesWins ?? 0}.`:`Connect Four series finished.`); for(const p of room.players)p.result=p.id===winner?.id?(room.bestOf===1?"Winner":"Series winner"):winner?(room.bestOf===1?"Runner-up":"Runner-up"):"Finished"; log(room,{playerId:winner?.id??null,playerName:winner?.name??null,action:"finish",column:null,detail:room.status}); void finalizeSession("connect-four",room.code,room.createdAt,archiveStatus,archive(room),{winner:winner?.name??null,players:room.players.length,mode:room.matchMode,bestOf:room.bestOf,rounds:room.roundHistory.length,durationMs:Date.now()-room.createdAt}); emit(io,room); io.emit("platform:game-finished",{id:`connect-four-${room.code}-${room.actionSequence}`,game:"connect-four",gameTitle:"Connect Four",code:room.code,status:"game-finished",winner:winner?.name??null,message:room.status,at:room.updatedAt}); }
function finishRound(io:Server, room:Room, winner:Player|null, draw=false){ room.currentTurnPlayerId=null; room.roundWinnerPlayerId=winner?.id??null; room.draw=draw; if(winner)winner.seriesWins+=1; room.roundHistory.push({round:room.roundNumber,winnerPlayerId:winner?.id??null,winnerName:winner?.name??null,draw,moves:room.turnNumber}); const reached=winner && winner.seriesWins>=room.targetWins; if(room.bestOf===1){ finaliseMatch(io,room,winner,draw?"Connect Four ends in a draw.":`${winner?.name ?? "Winner"} connects four.`); return; } if(reached){ finaliseMatch(io,room,winner); return; } room.phase="round-over"; room.status=draw?`Round ${room.roundNumber} is a draw.`:`${winner?.name ?? "Winner"} wins round ${room.roundNumber}.`; for(const p of room.players)p.result=draw?"Round draw":p.id===winner?.id?"Round winner":"Round lost"; log(room,{playerId:winner?.id??null,playerName:winner?.name??null,action:"round",column:null,detail:room.status}); emit(io,room); }
function startRound(io:Server,room:Room){ room.phase="playing"; room.roundNumber+=1; room.board=Array(42).fill(0); room.turnNumber=0; room.lastDropIndex=null; room.roundWinnerPlayerId=null; room.draw=false; room.players.forEach(p=>p.result=null); const starter=room.players[(room.roundNumber-1)%2]; room.currentTurnPlayerId=starter?.id??null; room.status=starter?`${starter.name} starts round ${room.roundNumber}.`:"Waiting for players."; log(room,{playerId:null,playerName:null,action:"round",column:null,detail:`Round ${room.roundNumber} started.`}); emit(io,room); }
function play(io:Server, room:Room, player:Player, column:number):string|null{ if(room.phase!=="playing")return "Connect Four is not active."; if(room.currentTurnPlayerId!==player.id)return "It is not your turn."; const at=dropIndex(room.board,column); if(at<0)return "That column is full."; const disc:ConnectFourDisc=player.seat===0?1:2; room.board[at]=disc; room.lastDropIndex=at; room.turnNumber++; log(room,{playerId:player.id,playerName:player.name,action:"drop",column,detail:`${player.name} dropped a disc in column ${column+1}.`}); if(winning(room.board,disc)){ finishRound(io,room,player); return null; } if(!legalColumns(room.board).length){ finishRound(io,room,null,true); return null; } const next=other(room,player); room.currentTurnPlayerId=next?.id??null; room.status=next?`${next.name}'s turn.`:"Waiting for an opponent."; emit(io,room); return null; }
function choose(room:Room,p:Player,legal:number[]){ const disc:ConnectFourDisc=p.seat===0?1:2; const opp:ConnectFourDisc=disc===1?2:1; const win=legal.find(c=>{const b=[...room.board];b[dropIndex(b,c)]=disc;return winning(b,disc)}); if(win!==undefined)return win; if(p.aiDifficulty!=="easy"){ const block=legal.find(c=>{const b=[...room.board];b[dropIndex(b,c)]=opp;return winning(b,opp)}); if(block!==undefined)return block; } if(p.aiDifficulty==="hard"){ const order=[3,2,4,1,5,0,6]; const safe=order.filter(c=>legal.includes(c)).find(c=>{const b=[...room.board];b[dropIndex(b,c)]=disc; return !legalColumns(b).some(oc=>{const bb=[...b];bb[dropIndex(bb,oc)]=opp;return winning(bb,opp)});}); if(safe!==undefined)return safe; } const weighted=[3,3,2,4,1,5,0,6].filter(c=>legal.includes(c)); return weighted[Math.floor(Math.random()*weighted.length)]??legal[0]; }
function scheduleAi(io:Server,room:Room){ const old=aiTimers.get(room.code); if(old)clearTimeout(old); if(room.phase!=="playing")return; const p=room.players.find(x=>x.id===room.currentTurnPlayerId); if(!p?.isAi)return; aiTimers.set(room.code,setTimeout(()=>{ if(room.phase!=="playing"||room.currentTurnPlayerId!==p.id)return; const c=choose(room,p,legalColumns(room.board)); if(c>=0)play(io,room,p,c); },650)); }
function addAi(room:Room,d:ConnectFourAiDifficulty){ if(room.phase!=="lobby")return "AI can only be added before play."; if(room.players.length>=2)return "Connect Four supports two seats."; const used=new Set(room.players.map(p=>p.name)); const n=AI_NAMES.find(x=>!used.has(x))??`AI ${room.players.length+1}`; room.players.push({id:`c4-ai-${token()}`,reconnectToken:"",name:n,isHost:false,isAi:true,aiDifficulty:d,isConnected:true,seat:room.players.length,colour:room.players.length===0?"red":"yellow",result:null,seriesWins:0}); return null; }
export function getConnectFourRoomCount(){ return [...rooms.values()].filter(room=>room.phase!=="finished" && (room.players.some(player=>!player.isAi&&player.isConnected) || room.spectators.size>0)).length; }
export function getConnectFourChatIdentity(c:string,socketId:string){ const room=rooms.get(code(c)); if(!room)return null; const p=room.players.find(x=>x.id===socketId&&x.isConnected); if(p)return {name:p.name,role:"player" as const}; const s=room.spectators.get(socketId); return s?{name:s,role:"spectator" as const}:null; }
export function registerConnectFourHandlers(io:Server,socket:Socket){
 socket.on("connect-four:create",(payload:any,ack:(r:any)=>void)=>{ const c=code(payload?.code)||token().slice(0,6); if(rooms.has(c)&&rooms.get(c)?.phase!=="finished")return ack({ok:false,reason:"That Connect Four room already exists."}); const n=name(payload?.playerName); if(!n)return ack({ok:false,reason:"Enter a player name."}); const p:Player={id:socket.id,reconnectToken:token(),name:n,isHost:true,isAi:false,aiDifficulty:null,isConnected:true,seat:0,colour:"red",result:null,seriesWins:0}; const bo=bestOf(payload?.bestOf); const room:Room={code:c,createdAt:Date.now(),startedAt:null,updatedAt:Date.now(),phase:"lobby",matchMode:mode(payload?.matchMode),bestOf:bo,targetWins:Math.floor(bo/2)+1,roundNumber:0,roundHistory:[],players:[p],spectators:new Map(),board:Array(42).fill(0),currentTurnPlayerId:null,winnerPlayerId:null,roundWinnerPlayerId:null,draw:false,turnNumber:0,lastDropIndex:null,status:"Waiting for one more player.",actionSequence:0,actionLog:[]}; rooms.set(c,room); emit(io,room); ack({ok:true,code:c,playerId:p.id,reconnectToken:p.reconnectToken,state:publicState(room,p.id,false)}); });
 socket.on("connect-four:join",(payload:any,ack:(r:any)=>void)=>{ const room=rooms.get(code(payload?.code)); if(!room)return ack({ok:false,reason:"Connect Four room not found."}); if(room.phase!=="lobby"||room.players.length>=2)return ack({ok:false,reason:"That Connect Four table is full or already started."}); const n=name(payload?.playerName); if(!n)return ack({ok:false,reason:"Enter a player name."}); const p:Player={id:socket.id,reconnectToken:token(),name:n,isHost:false,isAi:false,aiDifficulty:null,isConnected:true,seat:1,colour:"yellow",result:null,seriesWins:0}; room.players.push(p); emit(io,room); ack({ok:true,code:room.code,playerId:p.id,reconnectToken:p.reconnectToken,state:publicState(room,p.id,false)}); });
 socket.on("connect-four:reconnect",(payload:any,ack:(r:any)=>void)=>{ const room=rooms.get(code(payload?.code)); const t=typeof payload?.reconnectToken==="string"?payload.reconnectToken.trim().toUpperCase():""; const p=room?.players.find(x=>x.reconnectToken===t&&!x.isAi); if(!room||!p)return ack({ok:false,reason:"That saved Connect Four seat is not available."}); const oldId=p.id; p.id=socket.id;p.isConnected=true; if(room.currentTurnPlayerId===oldId)room.currentTurnPlayerId=p.id; if(room.winnerPlayerId===oldId)room.winnerPlayerId=p.id; if(room.roundWinnerPlayerId===oldId)room.roundWinnerPlayerId=p.id; room.roundHistory=room.roundHistory.map(r=>r.winnerPlayerId===oldId?{...r,winnerPlayerId:p.id}:r); emit(io,room);ack({ok:true,code:room.code,playerId:p.id,reconnectToken:p.reconnectToken,state:publicState(room,p.id,false)}); });
 socket.on("connect-four:spectate",(payload:any,ack:(r:any)=>void)=>{ const room=rooms.get(code(payload?.code)); if(!room)return ack({ok:false,reason:"Connect Four room not found."}); room.spectators.set(socket.id,name(payload?.playerName)||"Spectator");emit(io,room);ack({ok:true,state:publicState(room,null,true)}); });
 socket.on("connect-four:add-ai",(payload:any,ack:(r:any)=>void)=>{ const room=rooms.get(code(payload?.code)); const host=room?.players.find(x=>x.id===socket.id&&x.isHost); if(!room||!host)return ack({ok:false,reason:"Only the host can add AI."}); const reason=addAi(room,difficulty(payload?.difficulty)); if(reason)return ack({ok:false,reason});emit(io,room);ack({ok:true,state:publicState(room,host.id,false)}); });
 socket.on("connect-four:remove-ai",(payload:any,ack:(r:any)=>void)=>{ const room=rooms.get(code(payload?.code)); const host=room?.players.find(x=>x.id===socket.id&&x.isHost); if(!room||!host||room.phase!=="lobby")return ack({ok:false,reason:"Only the host can remove AI before play."}); room.players=room.players.filter(x=>!(x.id===payload?.playerId&&x.isAi)); room.players.forEach((p,i)=>{p.seat=i;p.colour=i===0?"red":"yellow"});emit(io,room);ack({ok:true}); });
 socket.on("connect-four:start",(payload:any,ack:(r:any)=>void)=>{ const room=rooms.get(code(payload?.code)); const host=room?.players.find(x=>x.id===socket.id&&x.isHost); if(!room||!host)return ack({ok:false,reason:"Only the host can start Connect Four."});if(room.phase!=="lobby"&&room.phase!=="finished")return ack({ok:false,reason:"The current match is already in progress."}); if(room.players.length!==2)return ack({ok:false,reason:"Connect Four needs exactly two players."}); room.startedAt=Math.max(Date.now(),(room.startedAt??0)+1); room.players.forEach(p=>{p.seriesWins=0;p.result=null}); room.roundHistory=[];room.roundNumber=0;room.winnerPlayerId=null;log(room,{playerId:null,playerName:null,action:"table",column:null,detail:`Connect Four best-of-${room.bestOf} started.`});startRound(io,room);ack({ok:true}); });
 socket.on("connect-four:next-round",(payload:any,ack:(r:any)=>void)=>{ const room=rooms.get(code(payload?.code)); const host=room?.players.find(x=>x.id===socket.id&&x.isHost); if(!room||!host)return ack({ok:false,reason:"Only the host can start the next round."}); if(room.phase!=="round-over")return ack({ok:false,reason:"The next round is not ready yet."}); startRound(io,room);ack({ok:true}); });
 socket.on("connect-four:drop",(payload:any,ack:(r:any)=>void)=>{ const room=rooms.get(code(payload?.code)); const p=room?.players.find(x=>x.id===socket.id); if(!room||!p)return ack({ok:false,reason:"Connect Four seat not found."}); const reason=play(io,room,p,Number(payload?.column));if(reason)return ack({ok:false,reason});ack({ok:true}); });
 socket.on("connect-four:end-game",(payload:any,ack:(r:any)=>void)=>{ const room=rooms.get(code(payload?.code));const host=room?.players.find(x=>x.id===socket.id&&x.isHost);if(!room||!host)return ack({ok:false,reason:"Only the host can end the game."}); finaliseMatch(io,room,null,`${host.name} ended the Connect Four match.`,"host-ended");ack({ok:true}); });
 socket.on("connect-four:forfeit",(payload:any,ack:(r:any)=>void)=>{ const room=rooms.get(code(payload?.code));const p=room?.players.find(x=>x.id===socket.id&&!x.isAi);if(!room||!p)return ack({ok:false,reason:"Connect Four seat not found."});const winner=other(room,p);log(room,{playerId:p.id,playerName:p.name,action:"forfeit",column:null,detail:`${p.name} forfeited.`});if(winner){ winner.seriesWins=Math.max(winner.seriesWins,room.targetWins); finaliseMatch(io,room,winner,`${p.name} forfeited. ${winner.name} wins the series.`); }else finaliseMatch(io,room,null);ack({ok:true}); });
 socket.on("connect-four:leave",(payload:any,ack?:(r:any)=>void)=>{const room=rooms.get(code(payload?.code));const p=room?.players.find(x=>x.id===socket.id);if(p)p.isConnected=false;room?.spectators.delete(socket.id);if(room)emit(io,room);ack?.({ok:true});});
 socket.on("disconnect",()=>{for(const room of rooms.values()){const p=room.players.find(x=>x.id===socket.id);if(p){p.isConnected=false;emit(io,room)}if(room.spectators.delete(socket.id))emit(io,room)}});
}

export function getConnectFourLiveRoomSummaries(): HalieusLiveRoomSummary[] {
  return [...rooms.values()]
    .filter((room) => room.phase !== "finished" && (room.players.some((player) => !player.isAi && player.isConnected) || room.spectators.size > 0))
    .map((room) => ({
      game: "connect-four", gameTitle: "Connect Four", code: room.code, phase: room.phase, matchMode: room.matchMode, started: room.phase !== "lobby",
      createdAt: room.createdAt, startedAt: room.startedAt, updatedAt: room.updatedAt, playerCount: room.players.length, maximumPlayers: 2,
      humanPlayers: room.players.filter((player) => !player.isAi && player.isConnected).map((player) => player.name), aiCount: room.players.filter((player) => player.isAi).length, spectatorCount: room.spectators.size,
      joinable: room.phase === "lobby" && room.players.length < 2, spectatable: true,
    }));
}
export function closeAllConnectFourRooms(){ const count=getConnectFourRoomCount(); for(const timer of aiTimers.values())clearTimeout(timer);aiTimers.clear();rooms.clear();return count; }
