import type { CSSProperties } from "react";
import { BOARD_GRID_SIZE } from "../../../../../shared/games/mega-board/board";

export const lightTheme = {
    pageBackground: "#f4efe5",
    cardBackground: "#ffffff",
    secondaryBackground: "#f3f4f6",
    inputBackground: "#ffffff",
    text: "#171717",
    mutedText: "#5f6670",
    border: "#d0cbc1",
};
export const darkTheme = {
    pageBackground: "#101317",
    cardBackground: "#1b2027",
    secondaryBackground: "#272d36",
    inputBackground: "#12161c",
    text: "#f5f7fa",
    mutedText: "#b5bdc9",
    border: "#3f4855",
};
export const styles: Record<string, CSSProperties> = {
    page: {
        minHeight: "100vh",
        display: "grid",
        placeItems: "center",
        padding: "24px",
        fontFamily: "Arial, sans-serif",
        transition: "background 180ms ease, color 180ms ease",
    },
    card: {
        width: "100%",
        maxWidth: "500px",
        boxSizing: "border-box",
        padding: "32px",
        border: "1px solid",
        borderRadius: "20px",
        boxShadow: "0 18px 50px rgba(0, 0, 0, 0.18)",
    },
    themeButton: {
        position: "fixed",
        top: "20px",
        right: "20px",
        padding: "10px 14px",
        border: "1px solid",
        borderRadius: "10px",
        fontWeight: 700,
        cursor: "pointer",
    },
    eyebrow: {
        margin: "0 0 8px",
        textTransform: "uppercase",
        letterSpacing: "0.12em",
        fontSize: "12px",
        fontWeight: 700,
        color: "var(--mm-warning)",
    },
    title: {
        margin: 0,
        fontSize: "36px",
    },
    status: {
        margin: "12px 0 28px",
    },
    form: {
        display: "grid",
        gap: "20px",
    },
    label: {
        display: "grid",
        gap: "8px",
        fontWeight: 700,
    },
    input: {
        width: "100%",
        boxSizing: "border-box",
        padding: "12px 14px",
        border: "1px solid",
        borderRadius: "10px",
        fontSize: "16px",
    },
    roomRow: {
        display: "flex",
        gap: "10px",
    },
    checkboxRow: {
        display: "flex",
        alignItems: "center",
        gap: "10px",
        fontWeight: 700,
    },
    primaryButton: {
        padding: "14px 18px",
        border: "none",
        borderRadius: "10px",
        background: "#147d3f",
        color: "#ffffff",
        fontSize: "16px",
        fontWeight: 700,
        cursor: "pointer",
    },
    secondaryButton: {
        padding: "12px 16px",
        border: "1px solid",
        borderRadius: "10px",
        fontWeight: 700,
        cursor: "pointer",
    },
    secondaryActionButton: {
        padding: "14px 18px",
        border: "1px solid #147d3f",
        borderRadius: "10px",
        background: "transparent",
        color: "var(--mm-positive)",
        fontSize: "16px",
        fontWeight: 700,
        cursor: "pointer",
    },
    divider: {
        textAlign: "center",
        fontSize: "13px",
        fontWeight: 700,
        opacity: 0.6,
    },
    dangerButton: {
        padding: "14px 18px",
        border: "none",
        borderRadius: "10px",
        background: "#b42318",
        color: "#ffffff",
        fontSize: "16px",
        fontWeight: 700,
        cursor: "pointer",
    },
    message: {
        marginTop: "20px",
        padding: "12px",
        border: "1px solid",
        borderRadius: "10px",
        wordBreak: "break-word",
    },
    roomCodeBox: {
        display: "grid",
        justifyItems: "center",
        gap: "8px",
        marginTop: "24px",
        padding: "20px",
        border: "1px solid",
        borderRadius: "14px",
    },
    roomCodeLabel: {
        fontSize: "12px",
        fontWeight: 700,
        letterSpacing: "0.12em",
        textTransform: "uppercase",
    },
    roomCode: {
        fontSize: "32px",
        letterSpacing: "0.18em",
    },
    lobbyDetails: {
        display: "flex",
        flexWrap: "wrap",
        justifyContent: "space-between",
        gap: "12px",
        marginTop: "20px",
        fontSize: "14px",
    },
    playersSection: {
        marginTop: "28px",
    },
    sectionTitle: {
        margin: "0 0 12px",
        fontSize: "20px",
    },
    playerList: {
        display: "grid",
        gap: "10px",
    },
    playerRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "12px",
        border: "1px solid",
        borderRadius: "12px",
    },
    playerIdentity: {
        display: "flex",
        alignItems: "center",
        gap: "12px",
    },
    playerToken: {
        display: "grid",
        placeItems: "center",
        width: "38px",
        height: "38px",
        borderRadius: "50%",
        background: "#147d3f",
        color: "#ffffff",
        fontWeight: 800,
    },
    youLabel: {
        marginTop: "3px",
        fontSize: "11px",
        opacity: 0.7,
    },
    hostBadge: {
        padding: "6px 9px",
        borderRadius: "999px",
        background: "#e6b94f",
        color: "#221900",
        fontSize: "12px",
        fontWeight: 800,
    },
    waitingMessage: {
        margin: "14px 0 0",
        textAlign: "center",
        fontSize: "14px",
    },
    buttonGroup: {
        display: "grid",
        gap: "10px",
        marginTop: "24px",
    },
    gamePage: {
        minHeight: "100vh",
        boxSizing: "border-box",
        padding: "24px",
        fontFamily: "Arial, sans-serif",
        transition: "background 180ms ease, color 180ms ease",
    },
    gameHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        flexWrap: "wrap",
        gap: "18px",
        maxWidth: "1400px",
        margin: "0 auto 20px",
        padding: "18px 22px",
        border: "1px solid",
        borderRadius: "16px",
    },
    gameTitle: {
        margin: 0,
        fontSize: "28px",
    },
    gameHeaderDetails: {
        display: "flex",
        flexWrap: "wrap",
        alignItems: "center",
        gap: "8px",
        paddingRight: "130px",
        fontSize: "14px",
    },
    gameLayout: {
        display: "grid",
        gridTemplateColumns: "minmax(0, 1fr) minmax(260px, 300px)",
        gap: "20px",
        width: "100%",
        maxWidth: "1400px",
        margin: "0 auto",
        alignItems: "start",
    },
    boardFrame: {
        minWidth: 0,
        padding: "18px",
        border: "1px solid",
        borderRadius: "18px",
        overflow: "hidden",
    },
    board: {
        display: "grid",
        gridTemplateColumns: `repeat(${BOARD_GRID_SIZE}, minmax(0, 1fr))`,
        gridTemplateRows: `repeat(${BOARD_GRID_SIZE}, minmax(0, 1fr))`,
        width: "100%",
        maxWidth: "920px",
        aspectRatio: "1 / 1",
        margin: "0 auto",
        border: "3px solid",
        boxSizing: "border-box",
    },
    boardSpace: {
        position: "relative",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: "4px",
        minWidth: 0,
        padding: "4px",
        border: "1px solid",
        boxSizing: "border-box",
        textAlign: "center",
        overflow: "hidden",
    },
    spaceNumber: {
        position: "absolute",
        top: "3px",
        left: "4px",
        fontSize: "7px",
        opacity: 0.55,
    },
    spaceName: {
        lineHeight: 1.05,
        textTransform: "none",
        letterSpacing: "-0.01em",
        fontWeight: 800,
        overflowWrap: "anywhere",
    },
    boardCentre: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        padding: "28px",
        textAlign: "center",
    },
    boardCentreEyebrow: {
        margin: "0 0 12px",
        fontSize: "12px",
        fontWeight: 800,
        letterSpacing: "0.12em",
        textTransform: "uppercase",
        opacity: 0.7,
    },
    boardLogo: {
        margin: 0,
        fontSize: "clamp(32px, 5vw, 68px)",
        lineHeight: 0.9,
        letterSpacing: "-0.04em",
    },
    turnPanel: {
        display: "grid",
        gap: "5px",
        minWidth: "180px",
        marginTop: "28px",
        padding: "14px 18px",
        border: "1px solid",
        borderRadius: "12px",
    },
    turnLabel: {
        fontSize: "11px",
        fontWeight: 700,
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        opacity: 0.65,
    },
    rollButton: {
        marginTop: "16px",
        padding: "12px 24px",
        border: "none",
        borderRadius: "10px",
        background: "#147d3f",
        color: "#ffffff",
        fontSize: "15px",
        fontWeight: 800,
    },
    boardStatus: {
        margin: "12px 0 0",
        fontSize: "13px",
    },
    gameSidebar: {
        display: "grid",
        gap: "14px",
        padding: "20px",
        border: "1px solid",
        borderRadius: "18px",
    },
    sidebarTitle: {
        margin: 0,
        fontSize: "26px",
    },
    sidebarSubtitle: {
        margin: "6px 0 0",
        fontSize: "13px",
    },
    playerGameList: {
        display: "grid",
        gap: "9px",
    },
    gamePlayerCard: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "10px",
        padding: "10px",
        border: "1px solid",
        borderRadius: "12px",
    },
    playerPosition: {
        marginTop: "3px",
        fontSize: "11px",
    },
    playerOrder: {
        display: "grid",
        placeItems: "center",
        minWidth: "28px",
        height: "28px",
        borderRadius: "50%",
        background: "#e6b94f",
        color: "#221900",
        fontSize: "11px",
        fontWeight: 800,
    },
    gameInfoBox: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "12px",
        padding: "12px",
        border: "1px solid",
        borderRadius: "10px",
        fontSize: "13px",
    },
    orderingCard: {
        width: "100%",
        maxWidth: "720px",
        boxSizing: "border-box",
        margin: "70px auto 0",
        padding: "32px",
        border: "1px solid",
        borderRadius: "20px",
        boxShadow: "0 18px 50px rgba(0, 0, 0, 0.18)",
    },
    orderingIntro: {
        margin: "12px 0 22px",
        lineHeight: 1.5,
    },
    orderingRoundBox: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: "18px",
        padding: "12px 14px",
        border: "1px solid",
        borderRadius: "12px",
    },
    orderingPlayerList: {
        display: "grid",
        gap: "10px",
    },
    orderingPlayerRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "12px",
        padding: "12px",
        border: "1px solid",
        borderRadius: "12px",
    },
    orderingStatusBadge: {
        padding: "7px 10px",
        borderRadius: "999px",
        fontSize: "12px",
        fontWeight: 800,
        whiteSpace: "nowrap",
    },
    orderingWaitingText: {
        margin: "14px 0 0",
        textAlign: "center",
        fontSize: "13px",
    },
    spaceTokens: {
        display: "flex",
        flexWrap: "wrap",
        justifyContent: "center",
        gap: "2px",
        maxWidth: "100%",
    },
    boardPlayerToken: {
        display: "grid",
        placeItems: "center",
        width: "14px",
        height: "14px",
        borderRadius: "50%",
        color: "#ffffff",
        fontSize: "7px",
        fontWeight: 800,
        border: "1px solid rgba(255, 255, 255, 0.8)",
        boxShadow: "0 1px 3px rgba(0, 0, 0, 0.35)",
    },
    propertyColourStrip: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        height: "7px",
        borderBottom: "1px solid rgba(0, 0, 0, 0.45)",
    },
    ownerMarker: {
        position: "absolute",
        top: "9px",
        right: "3px",
        display: "grid",
        placeItems: "center",
        width: "13px",
        height: "13px",
        borderRadius: "50%",
        color: "#ffffff",
        fontSize: "7px",
        fontWeight: 900,
        border: "1px solid rgba(255, 255, 255, 0.9)",
        boxShadow: "0 1px 3px rgba(0, 0, 0, 0.45)",
    },
    purchasePanel: {
        width: "min(360px, 100%)",
        boxSizing: "border-box",
        marginTop: "18px",
        padding: "16px",
        border: "2px solid",
        borderRadius: "14px",
        boxShadow: "0 10px 24px rgba(0, 0, 0, 0.14)",
    },
    purchaseEyebrow: {
        display: "block",
        marginBottom: "5px",
        fontSize: "10px",
        fontWeight: 800,
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        opacity: 0.65,
    },
    purchaseTitle: {
        display: "block",
        fontSize: "20px",
    },
    purchasePrice: {
        display: "block",
        marginTop: "5px",
        fontSize: "22px",
        fontWeight: 900,
        color: "var(--mm-positive)",
    },
    purchaseText: {
        margin: "10px 0 0",
        fontSize: "13px",
    },
    purchaseActions: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "10px",
        marginTop: "14px",
    },
    buyButton: {
        padding: "11px 14px",
        border: "none",
        borderRadius: "9px",
        background: "#147d3f",
        color: "#ffffff",
        fontWeight: 800,
    },
    passButton: {
        padding: "11px 14px",
        border: "1px solid",
        borderRadius: "9px",
        background: "transparent",
        fontWeight: 800,
        cursor: "pointer",
    },
    gameMessage: {
        width: "min(360px, 100%)",
        boxSizing: "border-box",
        margin: "14px 0 0",
        padding: "10px 12px",
        border: "1px solid",
        borderRadius: "9px",
        fontSize: "12px",
    },

    propertyManager: {
        display: "grid",
        gap: "12px",
        marginTop: "8px",
        paddingTop: "16px",
        borderTop: "1px solid rgba(128, 128, 128, 0.28)",
    },
    propertyManagerTitle: {
        margin: 0,
        fontSize: "18px",
    },
    propertyManagerText: {
        margin: "5px 0 0",
        fontSize: "12px",
        lineHeight: 1.45,
    },
    bankInventory: {
        display: "flex",
        justifyContent: "space-between",
        gap: "8px",
        padding: "10px",
        border: "1px solid",
        borderRadius: "10px",
        fontSize: "12px",
        fontWeight: 800,
    },
    emptyPropertyText: {
        margin: 0,
        fontSize: "12px",
        textAlign: "center",
    },
    propertyManagementList: {
        display: "grid",
        gap: "9px",
        maxHeight: "360px",
        overflowY: "auto",
        paddingRight: "2px",
    },
    propertyManagementCard: {
        position: "relative",
        display: "grid",
        gridTemplateColumns: "8px minmax(0, 1fr) auto",
        alignItems: "center",
        gap: "10px",
        padding: "10px",
        border: "1px solid",
        borderRadius: "11px",
        overflow: "hidden",
    },
    propertyManagerColour: {
        alignSelf: "stretch",
        width: "8px",
        minHeight: "54px",
        borderRadius: "999px",
    },
    propertyManagerBody: {
        display: "grid",
        minWidth: 0,
        gap: "3px",
    },
    propertyManagerMeta: {
        fontSize: "10px",
    },
    propertyManagerWarning: {
        fontSize: "9px",
        lineHeight: 1.3,
    },
    buildButton: {
        padding: "8px 10px",
        border: "none",
        borderRadius: "8px",
        background: "#147d3f",
        color: "#ffffff",
        fontSize: "11px",
        fontWeight: 800,
    },
    developmentBadge: {
        position: "absolute",
        bottom: "2px",
        right: "2px",
        padding: "1px 3px",
        borderRadius: "4px",
        background: "rgba(0, 0, 0, 0.7)",
        color: "#ffffff",
        fontSize: "7px",
        fontWeight: 800,
        lineHeight: 1.2,
    },

    tradePanel: {
        display: "grid",
        gap: "12px",
        marginTop: "8px",
        paddingTop: "16px",
        borderTop: "1px solid rgba(128, 128, 128, 0.28)",
    },
    tradeTitle: {
        margin: 0,
        fontSize: "18px",
    },
    tradeHelp: {
        margin: "5px 0 0",
        fontSize: "11px",
        lineHeight: 1.4,
    },
    tradeLabel: {
        display: "grid",
        gap: "6px",
        fontSize: "12px",
        fontWeight: 700,
    },
    tradeInput: {
        width: "100%",
        boxSizing: "border-box",
        padding: "9px 10px",
        border: "1px solid",
        borderRadius: "8px",
        fontSize: "12px",
    },
    tradeColumns: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "10px",
    },
    tradeColumn: {
        display: "grid",
        alignContent: "start",
        gap: "7px",
        minWidth: 0,
        padding: "10px",
        border: "1px solid rgba(128, 128, 128, 0.25)",
        borderRadius: "10px",
    },
    tradeCheckRow: {
        display: "flex",
        alignItems: "flex-start",
        gap: "6px",
        fontSize: "10px",
        lineHeight: 1.3,
    },
    tradeSummary: {
        display: "grid",
        gap: "6px",
        padding: "12px",
        border: "1px solid",
        borderRadius: "10px",
        fontSize: "12px",
    },
    tradeDivider: {
        margin: "4px 0",
        textAlign: "center",
        fontWeight: 800,
        textTransform: "uppercase",
        opacity: 0.6,
    },
    tradeButtons: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "8px",
    },
    tradeSpecialItems: {
        display: "grid",
        gap: "6px",
        marginTop: "4px",
        paddingTop: "8px",
        borderTop: "1px solid rgba(128, 128, 128, 0.22)",
    },
    tradeSectionLabel: {
        fontSize: "10px",
        fontWeight: 900,
        textTransform: "uppercase",
        letterSpacing: "0.08em",
        opacity: 0.68,
    },

    assetPanel: {
        display: "grid",
        gap: "12px",
        marginTop: "8px",
        paddingTop: "16px",
        borderTop: "1px solid rgba(128, 128, 128, 0.28)",
    },
    assetTitle: {
        margin: 0,
        fontSize: "18px",
    },
    assetHelp: {
        margin: "5px 0 0",
        fontSize: "11px",
        lineHeight: 1.4,
    },
    assetList: {
        display: "grid",
        gap: "9px",
        maxHeight: "360px",
        overflowY: "auto",
    },
    assetCard: {
        display: "grid",
        gap: "9px",
        padding: "10px",
        border: "1px solid",
        borderRadius: "10px",
    },
    assetBody: {
        display: "grid",
        gap: "3px",
    },
    assetMeta: {
        fontSize: "10px",
        lineHeight: 1.35,
    },
    assetButtons: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "7px",
    },
    assetButton: {
        padding: "8px",
        border: "none",
        borderRadius: "8px",
        background: "#a97819",
        color: "#ffffff",
        fontSize: "10px",
        fontWeight: 800,
    },
    depotButton: {
        padding: "8px",
        border: "none",
        borderRadius: "8px",
        background: "#2563eb",
        color: "#ffffff",
        fontSize: "10px",
        fontWeight: 800,
    },
    sellButton: {
        padding: "8px",
        border: "none",
        borderRadius: "8px",
        background: "#b42318",
        color: "#ffffff",
        fontSize: "10px",
        fontWeight: 800,
    },
    mortgageBadge: {
        position: "absolute",
        right: "2px",
        top: "2px",
        display: "grid",
        placeItems: "center",
        width: "13px",
        height: "13px",
        borderRadius: "3px",
        background: "#b42318",
        color: "#ffffff",
        fontSize: "7px",
        fontWeight: 900,
    },

    debtPanel: {
        display: "grid",
        gap: "12px",
        padding: "14px",
        border: "2px solid",
        borderRadius: "12px",
    },
    debtTitle: {
        margin: 0,
        fontSize: "19px",
    },
    debtFigures: {
        display: "grid",
        gridTemplateColumns: "repeat(3, 1fr)",
        gap: "8px",
    },
    debtReason: {
        margin: 0,
        fontSize: "11px",
        lineHeight: 1.4,
    },
    debtHelp: {
        margin: 0,
        fontSize: "11px",
        lineHeight: 1.45,
    },
    debtButtons: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "8px",
    },
    winnerCard: {
        width: "100%",
        maxWidth: "560px",
        boxSizing: "border-box",
        padding: "40px",
        border: "1px solid",
        borderRadius: "24px",
        textAlign: "center",
        boxShadow: "0 20px 60px rgba(0, 0, 0, 0.22)",
    },
    winnerIcon: {
        fontSize: "72px",
        lineHeight: 1,
    },
    winnerTitle: {
        margin: "10px 0 0",
        fontSize: "44px",
    },
    winnerText: {
        margin: "8px 0 24px",
        fontSize: "17px",
    },
    winnerStats: {
        display: "grid",
        gridTemplateColumns: "repeat(3, 1fr)",
        gap: "10px",
        padding: "16px",
        border: "1px solid",
        borderRadius: "14px",
    },

    cardPopup: {
        display: "grid",
        justifyItems: "center",
        gap: "10px",
        width: "min(100%, 330px)",
        boxSizing: "border-box",
        padding: "22px",
        border: "3px solid",
        borderRadius: "16px",
        textAlign: "center",
        boxShadow: "0 16px 36px rgba(0, 0, 0, 0.24)",
    },
    cardDeckName: {
        fontSize: "12px",
        fontWeight: 900,
        letterSpacing: "0.18em",
    },
    cardIcon: {
        display: "grid",
        placeItems: "center",
        width: "52px",
        height: "52px",
        border: "3px solid #111111",
        borderRadius: "50%",
        fontSize: "27px",
        fontWeight: 900,
    },
    cardTitle: {
        margin: 0,
        fontSize: "22px",
    },
    cardDescription: {
        margin: 0,
        fontSize: "14px",
        fontWeight: 700,
        lineHeight: 1.45,
    },
    cardWaitingText: {
        margin: 0,
        fontSize: "12px",
        fontWeight: 700,
        opacity: 0.75,
    },
    cardContinueButton: {
        width: "100%",
        padding: "12px 16px",
        border: "2px solid #111111",
        borderRadius: "9px",
        background: "#ffffff",
        color: "#111111",
        fontSize: "14px",
        fontWeight: 900,
        cursor: "pointer",
    },

    turnPhaseLabel: {
        marginTop: "4px",
        fontSize: "10px",
        fontWeight: 800,
        textTransform: "capitalize",
        opacity: 0.68,
    },
    turnActionButtons: {
        display: "grid",
        gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
        gap: "9px",
        width: "100%",
    },
    endTurnButton: {
        padding: "12px 16px",
        border: "none",
        borderRadius: "10px",
        background: "#a97819",
        color: "#ffffff",
        fontSize: "14px",
        fontWeight: 800,
    },
    busTicketButton: {
        padding: "12px 16px",
        border: "none",
        borderRadius: "10px",
        background: "#dc2626",
        color: "#ffffff",
        fontSize: "14px",
        fontWeight: 800,
    },

    auctionPanel: {
        display: "grid",
        gap: "12px",
        width: "min(100%, 390px)",
        boxSizing: "border-box",
        padding: "18px",
        border: "3px solid",
        borderRadius: "16px",
        boxShadow: "0 16px 38px rgba(0, 0, 0, 0.24)",
    },
    auctionHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "12px",
    },
    auctionEyebrow: {
        fontSize: "10px",
        fontWeight: 900,
        letterSpacing: "0.17em",
        color: "var(--mm-warning)",
    },
    auctionTitle: {
        margin: "4px 0 0",
        fontSize: "22px",
    },
    auctionHammer: {
        fontSize: "34px",
    },
    auctionTimer: {
        display: "grid",
        justifyItems: "center",
        gap: "2px",
        padding: "11px 12px",
        border: "1px solid",
        borderRadius: "11px",
        textAlign: "center",
    },
    auctionTimerValue: {
        fontSize: "30px",
        lineHeight: 1,
        fontVariantNumeric: "tabular-nums",
    },
    auctionBidDisplay: {
        display: "grid",
        justifyItems: "center",
        gap: "3px",
        padding: "12px",
        border: "1px solid",
        borderRadius: "11px",
    },
    auctionPlayers: {
        display: "grid",
        gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
        gap: "7px",
        maxHeight: "190px",
        overflowY: "auto",
    },
    auctionPlayerRow: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        minWidth: 0,
        padding: "8px",
        border: "1px solid",
        borderRadius: "9px",
    },
    auctionPlayerToken: {
        display: "grid",
        placeItems: "center",
        flex: "0 0 auto",
        width: "28px",
        height: "28px",
        borderRadius: "50%",
        color: "#ffffff",
        fontSize: "11px",
        fontWeight: 900,
    },
    auctionPlayerBody: {
        display: "grid",
        minWidth: 0,
        gap: "2px",
        fontSize: "11px",
    },
    auctionQuickBids: {
        display: "grid",
        gridTemplateColumns: "repeat(3, 1fr)",
        gap: "7px",
    },
    auctionQuickButton: {
        padding: "8px",
        border: "1px solid",
        borderRadius: "8px",
        fontSize: "11px",
        fontWeight: 800,
        cursor: "pointer",
    },
    auctionBidLabel: {
        display: "grid",
        gap: "6px",
        fontSize: "11px",
        fontWeight: 800,
    },
    auctionBidInput: {
        width: "100%",
        boxSizing: "border-box",
        padding: "10px 12px",
        border: "1px solid",
        borderRadius: "9px",
        fontSize: "15px",
        fontWeight: 800,
    },
    auctionActions: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "8px",
    },
    auctionBidButton: {
        padding: "11px 12px",
        border: "none",
        borderRadius: "9px",
        background: "#147d3f",
        color: "#ffffff",
        fontSize: "12px",
        fontWeight: 900,
        cursor: "pointer",
    },
    auctionWithdrawButton: {
        padding: "11px 12px",
        border: "1px solid",
        borderRadius: "9px",
        background: "transparent",
        fontSize: "12px",
        fontWeight: 900,
        cursor: "pointer",
    },
    auctionWaitingText: {
        margin: 0,
        textAlign: "center",
        fontSize: "11px",
        lineHeight: 1.4,
    },

    freeParkingPot: {
        display: "grid",
        justifyItems: "center",
        gap: "2px",
        minWidth: "150px",
        padding: "9px 14px",
        border: "1px solid",
        borderRadius: "11px",
        textAlign: "center",
    },
    freeParkingPotLabel: {
        fontSize: "10px",
        fontWeight: 900,
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        opacity: 0.7,
    },
    freeParkingPotValue: {
        fontSize: "20px",
        fontVariantNumeric: "tabular-nums",
    },

    jailPanel: {
        display: "grid",
        gap: "12px",
        width: "min(100%, 420px)",
        boxSizing: "border-box",
        padding: "18px",
        border: "3px solid",
        borderRadius: "16px",
        boxShadow: "0 16px 38px rgba(0, 0, 0, 0.24)",
    },
    jailHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "12px",
    },
    jailEyebrow: {
        fontSize: "10px",
        fontWeight: 900,
        letterSpacing: "0.17em",
        textTransform: "uppercase",
        color: "var(--mm-negative)",
    },
    jailTitle: {
        margin: "4px 0 0",
        fontSize: "22px",
    },
    jailIcon: {
        fontSize: "34px",
    },
    jailSummary: {
        display: "grid",
        gap: "4px",
        padding: "11px 12px",
        border: "1px solid rgba(127, 127, 127, 0.45)",
        borderRadius: "11px",
        fontSize: "12px",
        lineHeight: 1.4,
    },
    jailStats: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "8px",
        fontSize: "12px",
        fontWeight: 800,
    },
    jailActions: {
        display: "grid",
        gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
        gap: "8px",
    },
    jailRollButton: {
        padding: "11px 10px",
        border: "none",
        borderRadius: "9px",
        background: "#147d3f",
        color: "#ffffff",
        fontSize: "11px",
        fontWeight: 900,
        cursor: "pointer",
    },
    jailPayButton: {
        padding: "11px 10px",
        border: "none",
        borderRadius: "9px",
        background: "#a97819",
        color: "#ffffff",
        fontSize: "11px",
        fontWeight: 900,
        cursor: "pointer",
    },
    jailCardButton: {
        padding: "11px 10px",
        border: "none",
        borderRadius: "9px",
        background: "#7c3aed",
        color: "#ffffff",
        fontSize: "11px",
        fontWeight: 900,
        cursor: "pointer",
    },
    jailWaitingText: {
        margin: 0,
        textAlign: "center",
        fontSize: "11px",
        fontWeight: 700,
        lineHeight: 1.4,
    },


    speedDiePanel: {
        display: "grid",
        gap: "12px",
        width: "min(100%, 440px)",
        boxSizing: "border-box",
        padding: "18px",
        border: "3px solid",
        borderRadius: "16px",
        boxShadow: "0 16px 38px rgba(0, 0, 0, 0.24)",
    },
    speedDieHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "12px",
    },
    speedDieEyebrow: {
        fontSize: "10px",
        fontWeight: 900,
        letterSpacing: "0.17em",
        textTransform: "uppercase",
        color: "var(--mm-link)",
    },
    speedDieTitle: {
        margin: "4px 0 0",
        fontSize: "22px",
    },
    speedDieIcon: {
        fontSize: "34px",
    },
    speedDieDescription: {
        margin: 0,
        fontSize: "12px",
        lineHeight: 1.5,
    },
    speedDieChoiceGrid: {
        display: "grid",
        gridTemplateColumns: "minmax(0, 1fr) auto",
        alignItems: "end",
        gap: "9px",
    },
    speedDieLabel: {
        display: "grid",
        gap: "6px",
        fontSize: "11px",
        fontWeight: 800,
    },
    speedDieSelect: {
        width: "100%",
        boxSizing: "border-box",
        padding: "10px 11px",
        border: "1px solid",
        borderRadius: "9px",
        fontSize: "12px",
        fontWeight: 700,
    },
    speedDieStats: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "8px",
        fontSize: "12px",
        fontWeight: 800,
    },
    speedDieActionButtons: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "8px",
    },
    speedDiePrimaryButton: {
        padding: "11px 12px",
        border: "none",
        borderRadius: "9px",
        background: "#2563eb",
        color: "#ffffff",
        fontSize: "12px",
        fontWeight: 900,
        cursor: "pointer",
    },
    speedDieTicketButton: {
        padding: "11px 12px",
        border: "none",
        borderRadius: "9px",
        background: "#dc2626",
        color: "#ffffff",
        fontSize: "12px",
        fontWeight: 900,
        cursor: "pointer",
    },
    speedDieWaitingText: {
        margin: 0,
        textAlign: "center",
        fontSize: "11px",
        fontWeight: 700,
        lineHeight: 1.4,
    },

    megaActionPanel: {
        display: "grid",
        gap: "11px",
        width: "min(100%, 460px)",
        boxSizing: "border-box",
        padding: "18px",
        border: "3px solid",
        borderRadius: "16px",
        boxShadow: "0 16px 38px rgba(0, 0, 0, 0.24)",
    },
    megaActionEyebrow: {
        margin: 0,
        fontSize: "10px",
        fontWeight: 900,
        letterSpacing: "0.17em",
        textTransform: "uppercase",
        color: "var(--mm-negative)",
    },
    megaActionTitle: {
        margin: 0,
        fontSize: "22px",
    },
    megaActionDescription: {
        margin: 0,
        fontSize: "12px",
        lineHeight: 1.5,
    },
    megaActionLabel: {
        display: "grid",
        gap: "6px",
        fontSize: "11px",
        fontWeight: 800,
    },
    megaActionSelect: {
        width: "100%",
        boxSizing: "border-box",
        padding: "10px 11px",
        border: "1px solid",
        borderRadius: "9px",
        fontSize: "12px",
        fontWeight: 700,
    },
    megaActionButtons: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "8px",
    },
    megaActionPrimaryButton: {
        padding: "11px 12px",
        border: "none",
        borderRadius: "9px",
        background: "#147d3f",
        color: "#ffffff",
        fontSize: "12px",
        fontWeight: 900,
        cursor: "pointer",
    },
    megaActionSecondaryButton: {
        padding: "11px 12px",
        border: "1px solid #64748b",
        borderRadius: "9px",
        background: "transparent",
        color: "inherit",
        fontSize: "12px",
        fontWeight: 900,
        cursor: "pointer",
    },
    megaActionTicketButton: {
        padding: "11px 12px",
        border: "none",
        borderRadius: "9px",
        background: "#dc2626",
        color: "#ffffff",
        fontSize: "12px",
        fontWeight: 900,
        cursor: "pointer",
    },
    megaActionWaitingText: {
        margin: 0,
        textAlign: "center",
        fontSize: "11px",
        fontWeight: 700,
        lineHeight: 1.4,
    },
};
