// Generated by scripts/release-integrity.mjs. Do not edit by hand.
export const RELEASE_FINGERPRINT = "hgr-3.7.0b-d22e64f245e9d43c";
export const RELEASE_SOURCE_HASH = "d22e64f245e9d43c736496a41c91522ba61b91c60682116f12aad8ce1fe2992a";
