import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
const read=(p)=>readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const json=(p)=>JSON.parse(read(p));
const displayVersion=read('VERSION').trim();
assert.match(displayVersion,/^(?:3\.7\.0[a-z]?|4\.\d+\.\d+)$/,'3.7.0 invariant should survive later HGR 4.x releases');
const npmVersion=displayVersion.replace(/^(\d+\.\d+\.\d+)([a-z])$/,'$1-$2');
for(const file of ['package.json','client/package.json','server/package.json','shared/package.json','desktop/package.json']) assert.equal(json(file).version,npmVersion,`${file} version mismatch`);
for(const file of ['shared/games/ayo/types.ts','server/src/games/ayo/handlers.ts','client/src/games/ayo/AyoScreen.tsx','client/public/game-icons/ayo.svg','shared/games/word-board/types.ts','server/src/games/word-board/handlers.ts','client/src/games/word-board/WordBoardScreen.tsx','client/public/game-icons/word-board.svg','client/public/sw.js']) assert.ok(existsSync(new URL(`../${file}`,import.meta.url)),`${file} missing`);
const app=read('client/src/App.tsx'), home=read('client/src/platform/components/HomeScreen.tsx'), server=read('server/src/index.ts'), accounts=read('server/src/platform/accounts.ts'), shared=read('shared/platform/accounts.ts'), sockets=read('client/src/platform/network/sockets.ts'), manifest=read('client/public/site.webmanifest'), css=read('client/src/index.css');
assert.match(app,/AyoScreen/); assert.match(app,/WordBoardScreen/); assert.match(app,/"ayo:state"/); assert.match(app,/"word-board:state"/);
assert.match(server,/registerAyoHandlers/); assert.match(server,/registerWordBoardHandlers/); assert.match(server,/getAyoLiveRoomSummaries/); assert.match(server,/getWordBoardLiveRoomSummaries/);
assert.match(home,/REQUEST A GAME/); assert.match(home,/onCreateAyo/); assert.match(home,/onCreateWordBoard/); assert.match(home,/InstallAppButton/); assert.match(home,/NotificationPermissionButton/);
assert.match(shared,/HalieusGameRequestStatus/); assert.match(shared,/HalieusPlayerVisibility/); assert.match(accounts,/\/accounts\/game-requests/); assert.match(accounts,/\/admin\/accounts\/:accountId\/visibility/); assert.match(accounts,/Hidden Player/);
assert.match(sockets,/transports:\s*\["polling",\s*"websocket"\]/); assert.match(sockets,/tryAllTransports:\s*true/); assert.match(manifest,/"display":\s*"standalone"/); assert.match(css,/3\.7\.0 — Ayo/); assert.match(css,/3\.7\.0 — Word Board/);
const ayo=read('server/src/games/ayo/handlers.ts'), word=read('server/src/games/word-board/handlers.ts');
assert.match(ayo,/Array\(12\)\.fill\(4\)/); assert.match(ayo,/ayo:sow/); assert.match(ayo,/reconnectToken/); assert.match(ayo,/spectate/);
assert.match(word,/makeBoard\(\)/); assert.match(word,/word-board:play/); assert.match(word,/dictionaryMode/); assert.match(word,/rack:\s*viewer\?/); assert.match(word,/word-board:exchange/);
const nginx=read('deploy/oracle/nginx-halieus.remotewire.net.conf'); assert.match(nginx,/listen \[::\]:443 ssl http2/);
assert.ok(existsSync(new URL('../dev-tools/Oracle Quick Deploy/diagnose-ios-network.sh',import.meta.url)));
console.log('Halieus Game Room 3.7.0 platform + Ayo + Word Board regression: PASS');
