import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read=(p)=>readFileSync(p,"utf8");
const pkg=JSON.parse(read("package.json"));
const version=read("VERSION").trim();
const home=read("client/src/platform/components/HomeScreen.tsx");
const panel=read("client/src/platform/accounts/AccountPanel.tsx");
const accounts=read("server/src/platform/accounts.ts");
const css=read("client/src/index.css");
assert.match(pkg.version, /^\d+\.\d+\.\d+(?:-[a-z0-9.-]+)?$/i);
assert.equal(version,pkg.version);
assert.match(home,/type HomeView = "home" \| "games" \| "players"/);
assert.doesNotMatch(home,/view === "stats"/);
assert.doesNotMatch(home,/Games played<\/span><strong>\{stats\.played\}/);
assert.doesNotMatch(home,/Win rate/);
assert.match(home,/halieus-player-profile-card/);
assert.match(home,/accounts\/players\/\$\{encodeURIComponent\(selectedPlayerId\)\}\/stats/);
assert.match(home,/requestFullscreen/);
assert.match(home,/Exit Full Screen|Full Screen/);
assert.match(panel,/Personal game record/);
assert.match(panel,/accounts\/me\/stats/);
assert.match(accounts,/\/accounts\/players\/:accountId\/stats/);
assert.match(css,/Halieus 3\.4\.2b/);
assert.match(css,/html\[data-theme="dark"\] \.halieus-sidebar/);
assert.match(css,/\.halieus-featured-game img\{width:74px!important;height:74px!important/);
assert.match(css,/\.halieus-player-directory button/);
console.log("RC 3.4.2b shell recovery/player profile/fullscreen regression passed.");
