import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const read=(p)=>readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const json=(p)=>JSON.parse(read(p));
const displayVersion=read('VERSION').trim();
assert.match(displayVersion,/^(?:3\.7\.0[h-l]|4\.\d+\.\d+)$/);
const npmVersion=displayVersion.replace(/^(\d+\.\d+\.\d+)([a-z])$/,'$1-$2');
for(const file of ['package.json','client/package.json','server/package.json','shared/package.json','desktop/package.json']) assert.equal(json(file).version,npmVersion,`${file} version mismatch`);
const rootPackage=json('package.json');
assert.match(rootPackage.scripts['test:regression'],/regression-3\.7\.0g\.mjs.*regression-3\.7\.0h\.mjs/s,'Regression chain must preserve 3.7.0g before 3.7.0h');
const state=read('shared/games/mega-board/game-state.ts');
assert.match(state,/creditorShares\?: Array<\{/,'Pending debt must support multiple rent creditors');
const resolution=read('server/src/games/mega-board/utils/space-resolution.ts');
assert.match(resolution,/tiedOwnerIds/,'Highest-rent fallback must identify every owner tied at the maximum');
assert.match(resolution,/candidate\.rent === highest\.rent/,'Only exact maximum-rent ties may share the payment');
assert.match(resolution,/splitRentBetweenCreditors/,'Maximum rent must have a deterministic equal-split helper');
assert.match(resolution,/destination\.tiedOwnerIds\.length > 1/,'Shared rent must activate only for two or more different tied owners');
assert.match(resolution,/creditorShares: sharedRentShares/,'Unaffordable shared rent must retain all creditor shares through debt resolution');
assert.match(resolution,/Shared Maximum Rent/,'Players must receive an explicit shared-rent notice');
const debt=read('server/src/games/mega-board/utils/debt.ts');
assert.match(debt,/debt\.creditorShares/,'Debt settlement must consume multi-creditor shares');
assert.match(debt,/creditor\.cash \+= share\.amount/,'Each tied owner must receive their server-authoritative rent share');
assert.match(debt,/recordRentStats\(gameState, debtor, creditor, share\.amount\)/,'Shared payments must feed rent statistics per recipient');
assert.match(debt,/Remaining properties return to the Bank rather than being awarded arbitrarily to one creditor/,'Shared-rent bankruptcy must not arbitrarily award all assets to one tied owner');
const reconnect=read('server/src/games/mega-board/utils/reconnection.ts');
assert.match(reconnect,/creditorShares.*map/s,'Shared creditor IDs must survive seat reconnection/remapping');
const panel=read('client/src/games/mega-board/components/DebtPanel.tsx');
assert.match(panel,/Shared between:/,'Debt UI must identify every shared-rent creditor and amount');
const board=read('client/src/games/mega-board/components/GameBoard.tsx');
assert.match(board,/two or more different owners tie for that maximum rent/,'Auction help text must document the tie-sharing rule');
console.log('Halieus Game Room 3.7.0h shared maximum-rent regression: PASS');
