import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const read=(p)=>readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const json=(p)=>JSON.parse(read(p));
assert.match(read('VERSION').trim(),/^(?:3\.7\.0[d-z]|4\.0\.0)$/);
for(const file of ['package.json','client/package.json','server/package.json','shared/package.json','desktop/package.json']) assert.match(json(file).version,/^(?:3\.7\.0-[d-z]|4\.0\.0)$/,`${file} version mismatch`);
const ayo=read('client/src/games/ayo/AyoScreen.tsx');
assert.match(ayo,/buildSowFrames/,'Ayo must visualise relay sowing');
assert.match(ayo,/ayo-player-marker/,'Ayo must use readable seat/player markers');
assert.match(ayo,/ayo-board-ridge/,'Ayo board must use the compact traditional two-row board treatment');
assert.match(ayo,/--game-card/,'Ayo player surfaces must derive from the active theme instead of a white fallback');
const word=read('server/src/games/word-board/handlers.ts');
assert.match(word,/\["Q",1,10\]/,'Word Board must use standard Q tile value');
assert.match(word,/\["Z",1,10\]/,'Word Board must use standard Z tile value');
assert.match(word,/TRIPLE_WORD=new Set/,'Word Board must use a fixed classic premium-square layout');
assert.match(word,/first word must cross the centre square/i,'Word Board opening move must cross centre');
assert.match(word,/consecutivePasses>=6/,'Word Board must end after six consecutive scoreless turns');
assert.match(word,/resolved\.length===7\)total\+=50/,'Word Board must award the seven-tile bonus');
const wordScreen=read('client/src/games/word-board/WordBoardScreen.tsx');
assert.match(wordScreen,/Opening word crosses centre/,'Word Board must explain the centre opening rule in the UI');
assert.match(wordScreen,/word-board-player-card/,'Word Board must expose clear player/turn/score markers');
const css=read('client/src/index.css');
assert.match(css,/@keyframes ayoSeedPop/,'Ayo seed animation must be present');
assert.match(css,/wordCenterPulse/,'Word Board centre square must be visually emphasised on the opening move');
console.log('Halieus Game Room 3.7.0d Ayo/Word Board playtest refinement regression: PASS');
