import fs from 'node:fs';
import assert from 'node:assert/strict';
const read = (p) => fs.readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
const css = read('client/src/index.css');
const home = read('client/src/platform/components/HomeScreen.tsx');
const catalog = read('client/src/platform/games/catalog.ts');
const poker = read('client/src/games/poker/PokerScreen.tsx');
const pokerHandlers = read('server/src/games/poker/handlers.ts');
const blackjack = read('client/src/games/blackjack/BlackjackScreen.tsx');
const whot = read('client/src/games/whot/WhotScreen.tsx');
assert.match(css, /html\[data-theme="light"\] \.card-game-page/);
assert.match(css, /\.blackjack-page \{ --game-accent: #2563eb/);
assert.match(css, /\.whot-table \{[\s\S]*linear-gradient/);
assert.match(catalog, /id: "blackjack", name: "Blackjack"/);
assert.match(poker, /Forfeit/);
assert.match(blackjack, /Forfeit/);
assert.match(whot, /Forfeit seat/);
assert.match(pokerHandlers, /autopilotMode === "semi"|autopilotMode !== "full"/);
assert.match(css, /prefers-reduced-motion: reduce/);
console.log('RC 3.3.35 superseded-state regression checks passed.');
