import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, readFile, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
const data = await mkdtemp(resolve(tmpdir(), "hgr-part17-"));
process.env.HALIEUS_DATA_DIR = data;
const { registerTurnHandlers } = await import("../server/src/games/mega-board/handlers/turnHandlers.ts");
const { rooms } = await import("../server/src/games/mega-board/state/rooms.ts");
const { createInitialGameState } = await import("../shared/games/mega-board/game-state.ts");
const { captureProgression, registerProgressionIdentity, readPlayerProgression } = await import("../server/src/platform/progression.ts");
try {
 const room = { code:"FIX450", hostId:"host", players:[], started:false, gameState:null, blitz:false, createdAt:Date.now(), updatedAt:Date.now() }; rooms.set(room.code,room);
 const events = []; const io = { to: () => ({ emit: (...args) => events.push(args) }) };
 function handler(id) { const handlers={}; registerTurnHandlers(io,{id,on:(event,fn)=>handlers[event]=fn}); return (seconds) => { let result; handlers["game:set-turn-timer"]({code:room.code,seconds},r=>result=r); return result; }; }
 const host=handler("host"), guest=handler("guest");
 assert.equal(guest(60).ok,false); assert.equal(host(42).ok,false); assert.equal(host(90).ok,true); assert.equal(room.turnTimerSeconds,90); assert.equal(events.at(-1)[1].turnTimerSeconds,90);
 room.gameState=createInitialGameState(room.code,[],{turnTimerSeconds:room.turnTimerSeconds}); room.started=true; room.gameState.turnRollDeadline=12345;
 assert.equal(room.gameState.turnTimerSeconds,90); assert.equal(host(30).ok,false); assert.equal(room.gameState.turnRollDeadline,12345); assert.equal(room.gameState.turnTimerSeconds,90);
 console.log("PASS timer: host-only valid pregame setting, copied on start, live rejection preserves deadline");
 const clear=registerProgressionIdentity("socket",()=>({accountId:"account-a",beta:false}));
 const player={id:"socket",name:"Renamable",isConnected:true}; const state={startedAt:1000,players:[player],actionLog:[{sequence:1,at:2000,playerId:"socket",action:"roll"}]};
 captureProgression(state); state.actionLog.push({sequence:2,at:182000,playerId:"socket",action:"roll"}); captureProgression(state); captureProgression(state);
 assert.equal(player.progressionIdentity.activePlayMs,60000); assert.equal(player.progressionIdentity.accountId,"account-a"); clear();
 const directory=resolve(data,"sessions","finalized"); await mkdir(directory,{recursive:true});
 const archive={sessionId:"verified",game:"mega-board",status:"completed",finalisedAt:200000,state:{startedAt:1000,winnerPlayerId:"socket",players:[player],playerStats:{socket:{kassManeuvers:5,initiatedThreeWayDeals:1}}}};
 await writeFile(resolve(directory,"one.json"),JSON.stringify(archive)); await writeFile(resolve(directory,"duplicate.json"),JSON.stringify(archive));
 await writeFile(resolve(directory,"beta.json"),JSON.stringify({...archive,sessionId:"beta",state:{...archive.state,players:[{...player,progressionIdentity:{accountId:"account-a",beta:true}}]}}));
 await writeFile(resolve(directory,"spoof.json"),JSON.stringify({...archive,sessionId:"spoof",state:{...archive.state,players:[{id:"fake",name:"Renamable"}]}}));
 await writeFile(resolve(directory,"closed.json"),JSON.stringify({...archive,sessionId:"closed",status:"host-ended"}));
 const [first,second]=await Promise.all([readPlayerProgression("account-a"),readPlayerProgression("account-a")]);
 assert.deepEqual(first,second); assert.equal(first.played,1); assert.equal(first.wins,1); assert.equal(first.gamerScore,first.awards.reduce((n,a)=>n+a.points,0));
 assert.ok(first.awards.some(a=>a.id==="mega:kass-five")); assert.ok(first.awards.some(a=>a.id==="mega:three-way")); assert.equal((await readPlayerProgression("unrelated")).gamerScore,0);
 const cumulative=(id,count,at)=>({...archive,sessionId:id,finalisedAt:at,state:{...archive.state,players:[{...player,progressionIdentity:{accountId:"cumulative",beta:false}}],playerStats:{socket:{kassManeuvers:count}}}});
 await writeFile(resolve(directory,"cum-one.json"),JSON.stringify(cumulative("cum-one",2,210000)));
 assert.ok(!(await readPlayerProgression("cumulative")).awards.some(a=>a.id==="mega:kass-five"));
 await writeFile(resolve(directory,"cum-two.json"),JSON.stringify(cumulative("cum-two",3,220000)));
 assert.equal((await readPlayerProgression("cumulative")).awards.filter(a=>a.id==="mega:kass-five").length,1);
 const {finalizeSession}=await import("../server/src/platform/sessionArchive.ts");
 const match={startedAt:1000,players:[]};
 await Promise.all([finalizeSession("connect-four","REPLAY",1,"completed",match),finalizeSession("connect-four","REPLAY",1,"completed",match)]);
 match.startedAt=2000;await finalizeSession("connect-four","REPLAY",1,"completed",match);
 assert.equal((await readdir(directory)).filter(f=>f.startsWith("connect-four-REPLAY-")&&f.endsWith(".json")).length,2);
 assert.equal(JSON.parse(await readFile(resolve(directory,"connect-four-REPLAY-1000.json"),"utf8")).state.startedAt,1000);
 const {createPokerRoom,applyPokerAction}=await import("../server/src/games/poker/engine.ts");
 const seat=(id,n,cards)=>({id,name:id,seat:n,chips:100,totalCommitted:100,currentBet:0,folded:false,allIn:false,eliminated:false,acted:n===1,holeCards:cards});
 const royal=seat("royal",0,[{rank:14,suit:"H"},{rank:13,suit:"H"}]);
 const poker=createPokerRoom("ROYAL1",royal,100,5,10,"normal","casual","texas-holdem");poker.players.push(seat("other",1,[{rank:2,suit:"S"},{rank:3,suit:"S"}]));
 Object.assign(poker.hand,{phase:"river",currentTurnPlayerId:"royal",currentBet:0,pot:200,board:[{rank:12,suit:"H"},{rank:11,suit:"H"},{rank:10,suit:"H"},{rank:2,suit:"D"},{rank:3,suit:"C"}]});
 assert.equal(applyPokerAction(poker,"royal","check"),null);assert.equal(royal.progressionFeats?.royalFlush,true);
 const ludo={...archive,sessionId:"ludo-four",game:"ludo",state:{startedAt:1000,winnerPlayerId:"ludo",players:[{id:"ludo",pieces:Array.from({length:4},()=>({steps:57})),finishedCount:0,progressionIdentity:{accountId:"ludo-account",beta:false}}]}};
 await writeFile(resolve(directory,"ludo.json"),JSON.stringify(ludo));assert.ok((await readPlayerProgression("ludo-account")).awards.some(a=>a.id==="ludo:home-four"));
 console.log("PASS authoritative Poker royal-flush and Ludo four-home feats");
 console.log("PASS cumulative feats and independent immutable rematch archives");
 console.log("PASS progression: stable identity, bounded active time, deduplication, concurrent replay, Test Lab/closure/spoof exclusion, match feats");
} finally { const { flushRoomSave } = await import("../server/src/games/mega-board/utils/persistence.ts"); await flushRoomSave(); await rm(data,{recursive:true,force:true}); }
