import { ModalPortal } from "../../platform/components/ModalPortal";
import { useMemo, useState, type ReactNode } from "react";
import type { ConnectFourAiDifficulty, ConnectFourPublicState } from "../../../../shared/games/connect-four/types";
import { ConfirmDialog } from "../../platform/components/ConfirmDialog";
import { GameBrandIcon } from "../../platform/components/GameBrandIcon";
import { GAME_BY_ID } from "../../platform/games/catalog";
import { GameChrome } from "../../platform/components/GameChrome";
import { GameResultsScreen } from "../../platform/components/GameResultsScreen";
import { InviteLobbyPanel } from "../../platform/components/InviteLobbyPanel";
import { DisplaySettingsPanel } from "../../platform/components/DisplaySettingsPanel";

const CONNECT_FOUR_ACCENT = GAME_BY_ID["connect-four"].accent;
interface ThemeLike { pageBackground:string; cardBackground:string; secondaryBackground:string; inputBackground:string; text:string; mutedText:string; border:string; }
interface Props { state:ConnectFourPublicState; connectionStatus:string; message:string; darkMode:boolean; theme:ThemeLike; soundEnabled:boolean; onToggleFullscreen:()=>void; onToggleDarkMode:()=>void; onToggleSound:()=>void; onStart:()=>void; onNextRound:()=>void; onAddAi:(d:ConnectFourAiDifficulty)=>void; onRemoveAi:(id:string)=>void; onDrop:(column:number)=>void; onEndGame:()=>void; onForfeit:()=>void; onLeave:()=>void; roomActivity?:ReactNode; }

export function ConnectFourScreen({state,connectionStatus,message,darkMode,theme,soundEnabled,onToggleFullscreen,onToggleDarkMode,onToggleSound,onStart,onNextRound,onAddAi,onRemoveAi,onDrop,onEndGame,onForfeit,onLeave,roomActivity}:Props){
  const [menuOpen,setMenuOpen]=useState(false); const [inviteOpen,setInviteOpen]=useState(false); const [aiDifficulty,setAiDifficulty]=useState<ConnectFourAiDifficulty>("normal"); const [confirm,setConfirm]=useState<"forfeit"|"end"|null>(null);
  const viewer=state.players.find(p=>p.id===state.viewerPlayerId); const isHost=Boolean(viewer?.isHost); const current=state.players.find(p=>p.id===state.currentTurnPlayerId); const canAct=Boolean(viewer&&!state.isSpectator&&state.phase==="playing"&&current?.id===viewer.id);
  const rows=useMemo(()=>Array.from({length:6},(_,r)=>state.board.slice(r*7,r*7+7)),[state.board]);
  const resultRows=useMemo(()=>state.players.slice().sort((a,b)=>b.seriesWins-a.seriesWins).map((p,index)=>({id:p.id,rank:index+1,name:p.name,detail:`${p.seriesWins} round win${p.seriesWins===1?"":"s"}`,winner:p.id===state.winnerPlayerId,status:p.result??(index===0?"Series leader":"Player")})),[state.players]);
  const awards=useMemo(()=>[{title:"Series Winner",winner:state.players.find(p=>p.id===state.winnerPlayerId)?.name??"—",detail:`Best of ${state.bestOf}`}], [state.bestOf,state.players,state.winnerPlayerId]);
  const stats=useMemo(()=>[{label:"Rounds",value:String(state.roundHistory.length)},{label:"Format",value:`Best of ${state.bestOf}`},{label:"Moves",value:String(state.actionLog.filter(e=>e.action==="drop").length)},{label:"Mode",value:state.matchMode==="ranked"?"Ranked":"Casual"}], [state.actionLog,state.bestOf,state.matchMode,state.roundHistory.length]);
  const seriesScore=state.players.map(p=>`${p.name} ${p.seriesWins}`).join(" · ");

  return <main className="connect-four-page card-game-page page-enter" style={{background:theme.pageBackground,color:theme.text,["--game-accent" as string]:CONNECT_FOUR_ACCENT}}>
    <GameChrome accent={CONNECT_FOUR_ACCENT} onBackToGameRoom={onLeave} onOpenMenu={()=>setMenuOpen(true)} />
    <header className="card-game-header card-game-header-polished"><div className="card-game-brand-lockup"><GameBrandIcon game="connect-four"/><div><p>HALIEUS TABLE</p><h1>Connect Four</h1></div></div><div className="card-game-meta"><span>Room {state.code}</span><span>{state.matchMode==="ranked"?"🏆 Ranked":"Casual"}</span><span>Best of {state.bestOf}</span><span className={connectionStatus==="Connected"?"is-online":""}>{connectionStatus}</span></div></header>
    {state.phase==="lobby" ? <section className="card-game-lobby connect-four-lobby"><article className="card-game-lobby-card"><p className="modal-eyebrow">QUICK DUEL · BEST OF {state.bestOf}</p><h2>Drop. Connect. Repeat.</h2><p className="card-game-intro-copy">Two players alternate columns. First to connect four wins the round; first to {state.targetWins} round win{state.targetWins===1?"":"s"} takes the match.</p><div className="rules-contract"><strong>Match format</strong><span>{state.matchMode==="ranked"?"Ranked":"Casual"} · Best of {state.bestOf}</span><small>Round starters alternate automatically.</small></div>{isHost&&<div className="card-game-host-actions"><label className="card-game-ai-control">AI opponent<select value={aiDifficulty} onChange={e=>setAiDifficulty(e.target.value as ConnectFourAiDifficulty)}><option value="easy">Easy</option><option value="normal">Normal</option><option value="hard">Hard</option></select></label><button type="button" className="button-outline" disabled={state.players.length>=2} onClick={()=>onAddAi(aiDifficulty)}>Add AI</button><button type="button" className="button-primary" disabled={state.players.length!==2} onClick={onStart}>Start match</button></div>}<button type="button" className="button-muted" onClick={()=>setInviteOpen(true)}>Invite player</button></article><section className="card-game-roster"><header><div><p className="modal-eyebrow">SEATS</p><h2>Players</h2></div><span>{state.players.length}/2</span></header>{state.players.map(p=><article key={p.id} className="card-game-player-row"><span className={`connect-four-player-disc is-${p.colour}`} data-initial={p.name.trim().slice(0,1).toUpperCase() || "?"}/><div><strong>{p.name}</strong><small>{p.isHost?"Host":p.isAi?`${p.aiDifficulty} AI`:"Player"}</small></div>{isHost&&p.isAi&&<button type="button" onClick={()=>onRemoveAi(p.id)}>×</button>}</article>)}</section></section>
    : state.phase==="finished" ? <GameResultsScreen accent={CONNECT_FOUR_ACCENT} gameTitle="Connect Four" roomCode={state.code} headline={state.winnerPlayerId?`${state.players.find(p=>p.id===state.winnerPlayerId)?.name??"Winner"} wins the series`:"Connect Four finished"} subtitle={`${seriesScore} · Best of ${state.bestOf}`} rows={resultRows} stats={stats} awards={awards} finalEventTitle="Series complete" finalEventSteps={state.roundHistory.slice(-3).map(r=>r.draw?`Round ${r.round}: draw`:`Round ${r.round}: ${r.winnerName??"Winner"}`)} onDownloadReport={() => { const text=[`HALIEUS CONNECT FOUR · ${state.code}`,`Best of ${state.bestOf}`,seriesScore,...state.roundHistory.map(r=>`Round ${r.round}: ${r.draw?"Draw":r.winnerName??"Winner"} · ${r.moves} moves`)].join("\n"); const url=URL.createObjectURL(new Blob([text],{type:"text/plain"})); const a=document.createElement("a"); a.href=url; a.download=`connect-four-${state.code}-report.txt`; a.click(); URL.revokeObjectURL(url); }} onBackToGameRoom={onLeave} onPlayAgain={isHost?onStart:undefined} playAgainLabel="Play another series" />
    : <section className={`connect-four-live ${roomActivity ? "connect-four-live-with-room" : ""}`}><div className="connect-four-stage"><header className="connect-four-match-score"><div><p>ROUND {state.roundNumber} · BEST OF {state.bestOf}</p><h2>{state.status}</h2></div><div>{state.players.map(p=><span key={p.id}><i className={`connect-four-player-disc is-${p.colour}`} data-initial={p.name.trim().slice(0,1).toUpperCase() || "?"}/><strong>{p.name}</strong><b>{p.seriesWins}</b></span>)}</div></header><div className="connect-four-board" role="grid" aria-label="Connect Four board">{rows.map((row,r)=>row.map((disc,c)=>{const cellIndex=r*7+c;return <button key={`${r}-${c}`} type="button" className="connect-four-cell" disabled={!canAct||state.phase!=="playing"||state.board[c]!==0} onClick={()=>onDrop(c)} aria-label={`Column ${c+1}`}><span key={`${cellIndex}-${disc}`} style={cellIndex===state.lastDropIndex ? { ["--connect-drop-origin" as string]: `calc(-${r + 1}00% - ${(r + 1) * 7}px)` } : undefined} className={`${disc===1?"is-red":disc===2?"is-yellow":""} ${cellIndex===state.lastDropIndex?"is-last-drop":""}`}/></button>}))}</div><div className="connect-four-round-footer"><span>{state.roundHistory.length?state.roundHistory.map(r=>r.draw?`R${r.round}: Draw`:`R${r.round}: ${r.winnerName}`).join(" · "):"First round in progress"}</span>{isHost&&state.phase==="round-over"&&<button type="button" className="button-primary" onClick={onNextRound}>Start round {state.roundNumber+1}</button>}</div>{message&&<p className="status-toast">{message}</p>}</div>{roomActivity&&<aside className="connect-four-room-stack">{roomActivity}</aside>}</section>}
    {inviteOpen&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setInviteOpen(false)}><section className="card-game-invite-modal"><button type="button" className="icon-button invite-modal-close" onClick={()=>setInviteOpen(false)}>×</button><InviteLobbyPanel roomCode={state.code} darkMode={darkMode} gameTitle="Connect Four" invitePathPrefix="/connect-four" accent={CONNECT_FOUR_ACCENT} theme={theme}/></section></div>}
    {menuOpen&&<ModalPortal onClose={() => setMenuOpen(false)}><div className="modal-backdrop game-menu-top-layer" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setMenuOpen(false)}><section className="game-menu-modal card-game-menu-modal"><div className="modal-handle"/><header className="modal-heading-row"><div><p className="modal-eyebrow">Connect Four · Room {state.code}</p><h2>Game menu</h2></div><button type="button" className="icon-button" onClick={()=>setMenuOpen(false)}>×</button></header><button type="button" className="menu-action menu-action-primary" onClick={()=>setMenuOpen(false)}><span>▶</span><span><strong>Resume</strong><small>Return to the board</small></span></button><DisplaySettingsPanel darkMode={darkMode} soundEnabled={soundEnabled} onToggleDarkMode={onToggleDarkMode} onToggleSound={onToggleSound} onToggleFullscreen={onToggleFullscreen}/><button type="button" className="menu-action" onClick={onLeave}><span>←</span><span><strong>Back to Game Room</strong><small>Keep your seat recoverable</small></span></button>{viewer&&!state.isSpectator&&<button type="button" className="menu-action menu-action-danger" onClick={()=>{setMenuOpen(false);setConfirm("forfeit")}}><span>⚑</span><span><strong>Forfeit</strong><small>Leave this match permanently</small></span></button>}{isHost&&<button type="button" className="menu-action menu-action-danger" onClick={()=>{setMenuOpen(false);setConfirm("end")}}><span>■</span><span><strong>End match</strong><small>Finalise this room for everyone</small></span></button>}</section></div></ModalPortal>}
    <ConfirmDialog open={confirm!==null} title={confirm==="end"?"End Connect Four?":"Forfeit Connect Four?"} message={confirm==="end"?"This will end the full series for everyone and archive the session.":"Your opponent will win the series and your seat will be closed."} confirmLabel={confirm==="end"?"End match":"Forfeit"} destructive onCancel={()=>setConfirm(null)} onConfirm={()=>{const action=confirm;setConfirm(null);if(action==="end")onEndGame();else onForfeit();}}/>
  </main>;
}
