import { randomBytes } from "node:crypto";
import type { Server, Socket } from "socket.io";
import type { HalieusLiveRoomSummary } from "../../../../shared/platform/live-games.js";
import type { HiddenDictatorActionLogEntry, HiddenDictatorAiDifficulty, HiddenDictatorMatchMode, HiddenDictatorPolicy, HiddenDictatorPublicPlayer, HiddenDictatorPublicState, HiddenDictatorRole } from "../../../../shared/games/hidden-dictator/types.js";
import { finalizeSession, recordWorkingSession } from "../../platform/sessionArchive.js";
interface Player extends HiddenDictatorPublicPlayer { reconnectToken:string; role:HiddenDictatorRole|null; vote:"approve"|"reject"|null; }
interface Room { code:string;createdAt:number;startedAt:number|null;updatedAt:number;phase:HiddenDictatorPublicState["phase"];matchMode:HiddenDictatorMatchMode;players:Player[];spectators:Map<string,string>;speakerPlayerId:string|null;nominatedDeputyId:string|null;civicPolicies:number;controlPolicies:number;failedVotes:number;roundNumber:number;status:string;winner:"citizens"|"authoritarians"|null;deck:HiddenDictatorPolicy[];speakerHand:HiddenDictatorPolicy[];deputyHand:HiddenDictatorPolicy[];revealedVotes:Array<{playerId:string;vote:"approve"|"reject"}>|null;actionSequence:number;actionLog:HiddenDictatorActionLogEntry[]; }
const rooms=new Map<string,Room>();const timers=new Map<string,NodeJS.Timeout>();const AI_NAMES=["Rook","Vesper","Nova","Mira","Sable","Orion","Vale","Echo"];
const token=()=>randomBytes(8).toString("base64url").slice(0,10).toUpperCase();const cleanCode=(v:unknown)=>typeof v==="string"?v.trim().toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6):"";const cleanName=(v:unknown)=>typeof v==="string"?v.trim().slice(0,24):"";const mode=(v:unknown):HiddenDictatorMatchMode=>v==="ranked"?"ranked":"casual";const diff=(v:unknown):HiddenDictatorAiDifficulty=>v==="easy"||v==="hard"?v:"normal";
function shuffle<T>(items:T[]):T[]{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function pub(p:Player):HiddenDictatorPublicPlayer{return{id:p.id,name:p.name,isHost:p.isHost,isAi:p.isAi,aiDifficulty:p.aiDifficulty,isConnected:p.isConnected,seat:p.seat,result:p.result};}
function known(room:Room,viewer:Player|null){if(!viewer?.role)return[];if(viewer.role==="citizen")return[];return room.players.filter(p=>p.role==="authoritarian"||p.role==="dictator").map(p=>p.id);}
function state(room:Room,viewerId:string|null,isSpectator:boolean):HiddenDictatorPublicState{const viewer=viewerId?room.players.find(p=>p.id===viewerId)??null:null;const hand=viewer&&room.phase==="speaker-policy"&&viewer.id===room.speakerPlayerId?room.speakerHand:viewer&&room.phase==="deputy-policy"&&viewer.id===room.nominatedDeputyId?room.deputyHand:[];return{code:room.code,createdAt:room.createdAt,startedAt:room.startedAt,updatedAt:room.updatedAt,phase:room.phase,matchMode:room.matchMode,players:room.players.map(pub),spectatorCount:room.spectators.size,viewerPlayerId:viewerId,isSpectator,speakerPlayerId:room.speakerPlayerId,nominatedDeputyId:room.nominatedDeputyId,civicPolicies:room.civicPolicies,controlPolicies:room.controlPolicies,failedVotes:room.failedVotes,roundNumber:room.roundNumber,status:room.status,winner:room.winner,viewerRole:isSpectator?null:viewer?.role??null,knownAuthoritarianPlayerIds:isSpectator?[]:known(room,viewer),viewerVote:viewer?.vote??null,revealedVotes:room.revealedVotes,viewerPolicyHand:[...hand],actionLog:room.actionLog.slice(-160)};}
function log(room:Room,e:Omit<HiddenDictatorActionLogEntry,"sequence"|"at">){room.actionSequence++;room.actionLog.push({...e,sequence:room.actionSequence,at:Date.now()});if(room.actionLog.length>160)room.actionLog.splice(0,room.actionLog.length-160)}function archive(room:Room){return{...room,spectators:[...room.spectators.entries()]};}
function emit(io:Server,room:Room){room.updatedAt=Date.now();recordWorkingSession("hidden-dictator",room.code,room.createdAt,archive(room));for(const p of room.players)if(!p.isAi&&p.isConnected)io.to(p.id).emit("hidden-dictator:state",state(room,p.id,false));for(const id of room.spectators.keys())io.to(id).emit("hidden-dictator:state",state(room,null,true));scheduleAi(io,room);}
function rolesFor(n:number):HiddenDictatorRole[]{const auth=n<=6?1:n<=8?2:3;return shuffle(["dictator",...Array(auth).fill("authoritarian"),...Array(n-auth-1).fill("citizen")] as HiddenDictatorRole[])}
function policyDeck(){return shuffle([...Array(6).fill("civic"),...Array(11).fill("control")] as HiddenDictatorPolicy[])}function draw(room:Room,count:number){if(room.deck.length<count)room.deck=policyDeck();return room.deck.splice(0,count)}
function active(room:Room){return room.players.slice().sort((a,b)=>a.seat-b.seat)}function nextSpeaker(room:Room){const a=active(room);const i=a.findIndex(p=>p.id===room.speakerPlayerId);return a[(Math.max(i,0)+1)%a.length]??a[0]}
function startRound(io:Server,room:Room){room.roundNumber++;room.revealedVotes=null;room.nominatedDeputyId=null;for(const p of room.players)p.vote=null;const next=room.speakerPlayerId?nextSpeaker(room):active(room)[0];room.speakerPlayerId=next?.id??null;room.phase="nomination";room.status=`${next?.name??"Speaker"} must nominate a Deputy.`;emit(io,room)}
function finish(io:Server,room:Room,winner:"citizens"|"authoritarians",reason:string){room.phase="finished";room.winner=winner;room.status=reason;for(const p of room.players)p.result=(p.role==="citizen"?"citizens":"authoritarians")===winner?"Winner":"Defeated";log(room,{playerId:null,playerName:null,action:"finish",detail:reason});void finalizeSession("hidden-dictator",room.code,room.createdAt,"completed",archive(room),{winner:winner==="citizens"?"Citizens":"Authoritarians",players:room.players.length,mode:room.matchMode,durationMs:Date.now()-room.createdAt});emit(io,room);io.emit("platform:game-finished",{id:`hidden-dictator-${room.code}-${room.actionSequence}`,game:"hidden-dictator",gameTitle:"Hidden Dictator",code:room.code,status:"game-finished",winner:winner==="citizens"?"Citizens":"Authoritarians",message:reason,at:room.updatedAt});}
function enact(io:Server,room:Room,policy:HiddenDictatorPolicy){if(policy==="civic")room.civicPolicies++;else room.controlPolicies++;log(room,{playerId:room.nominatedDeputyId,playerName:room.players.find(p=>p.id===room.nominatedDeputyId)?.name??null,action:"policy",detail:`A ${policy} policy was enacted.`});room.speakerHand=[];room.deputyHand=[];room.failedVotes=0;if(room.civicPolicies>=5)return finish(io,room,"citizens","Citizens win by completing five Civic policies.");if(room.controlPolicies>=6)return finish(io,room,"authoritarians","Authoritarians win by completing six Control policies.");startRound(io,room)}
function resolveVotes(io:Server,room:Room){const votes=room.players.map(p=>({playerId:p.id,vote:p.vote??"reject" as const}));room.revealedVotes=votes;const yes=votes.filter(v=>v.vote==="approve").length;const approved=yes>room.players.length/2;log(room,{playerId:null,playerName:null,action:"vote",detail:`Government ${approved?"approved":"rejected"} ${yes}-${room.players.length-yes}.`});if(!approved){room.failedVotes++;if(room.failedVotes>=3){room.failedVotes=0;const forced=draw(room,1)[0]??"control";room.status=`Three failed governments. A ${forced} policy is enacted automatically.`;return enact(io,room,forced)}return setTimeout(()=>startRound(io,room),650)}const deputy=room.players.find(p=>p.id===room.nominatedDeputyId);if(room.controlPolicies>=3&&deputy?.role==="dictator")return finish(io,room,"authoritarians","The Hidden Dictator was elected Deputy after three Control policies.");room.phase="speaker-policy";room.speakerHand=draw(room,3);room.status=`${room.players.find(p=>p.id===room.speakerPlayerId)?.name} is choosing policies.`;emit(io,room)}
function addAi(room:Room,d:HiddenDictatorAiDifficulty){if(room.phase!=="lobby")return"AI can only be added before play.";if(room.players.length>=10)return"Hidden Dictator supports up to 10 players.";const used=new Set(room.players.map(p=>p.name));const n=AI_NAMES.find(x=>!used.has(x))??`AI ${room.players.length+1}`;room.players.push({id:`hd-ai-${token()}`,reconnectToken:"",name:n,isHost:false,isAi:true,aiDifficulty:d,isConnected:true,seat:room.players.length,result:null,role:null,vote:null});return null}
function aiVote(room:Room,p:Player){if(p.role==="authoritarian"||p.role==="dictator")return Math.random()<(p.aiDifficulty==="hard"?.82:.65)?"approve":"reject";return Math.random()<(p.aiDifficulty==="easy"?.58:.5)?"approve":"reject"}
function scheduleAi(io:Server,room:Room){const old=timers.get(room.code);if(old)clearTimeout(old);if(room.phase==="finished"||room.phase==="lobby")return;const speaker=room.players.find(p=>p.id===room.speakerPlayerId);const deputy=room.players.find(p=>p.id===room.nominatedDeputyId);if(room.phase==="nomination"&&speaker?.isAi){timers.set(room.code,setTimeout(()=>{const choices=room.players.filter(p=>p.id!==speaker.id);const preferred=speaker.role!=="citizen"?choices.filter(p=>p.role!=="citizen"):choices;const pick=preferred[Math.floor(Math.random()*preferred.length)]??choices[0];if(pick){room.nominatedDeputyId=pick.id;room.phase="voting";room.status=`${speaker.name} nominated ${pick.name}. Vote now.`;log(room,{playerId:speaker.id,playerName:speaker.name,action:"nominate",detail:room.status});emit(io,room)}},650));return}if(room.phase==="voting"){const ai=room.players.find(p=>p.isAi&&!p.vote);if(ai){timers.set(room.code,setTimeout(()=>{ai.vote=aiVote(room,ai);if(room.players.every(p=>p.vote))resolveVotes(io,room);else emit(io,room)},420));return}}if(room.phase==="speaker-policy"&&speaker?.isAi){timers.set(room.code,setTimeout(()=>{const discard=speaker.role==="citizen"?room.speakerHand.findIndex(p=>p==="control"):room.speakerHand.findIndex(p=>p==="civic");room.deputyHand=room.speakerHand.filter((_,i)=>i!==(discard>=0?discard:0));room.speakerHand=[];room.phase="deputy-policy";room.status=`${deputy?.name??"Deputy"} is choosing the enacted policy.`;emit(io,room)},600));return}if(room.phase==="deputy-policy"&&deputy?.isAi){timers.set(room.code,setTimeout(()=>{const want=deputy.role==="citizen"?"civic":"control";const policy=room.deputyHand.find(p=>p===want)??room.deputyHand[0]??"control";enact(io,room,policy)},600));}}
export function getHiddenDictatorRoomCount(){return [...rooms.values()].filter((room)=>room.phase!=="finished" && (room.players.some((player)=>!player.isAi&&player.isConnected) || room.spectators.size>0)).length}export function getHiddenDictatorChatIdentity(c:string,sid:string){const room=rooms.get(cleanCode(c));if(!room)return null;const p=room.players.find(x=>x.id===sid&&x.isConnected);if(p)return{name:p.name,role:"player" as const};const s=room.spectators.get(sid);return s?{name:s,role:"spectator" as const}:null}
export function registerHiddenDictatorHandlers(io:Server,socket:Socket){
 socket.on("hidden-dictator:create",(payload:any,ack:(r:any)=>void)=>{const c=cleanCode(payload?.code)||token().slice(0,6);if(rooms.has(c))return ack({ok:false,reason:"That Hidden Dictator room exists."});const n=cleanName(payload?.playerName);if(!n)return ack({ok:false,reason:"Enter a player name."});const p:Player={id:socket.id,reconnectToken:token(),name:n,isHost:true,isAi:false,aiDifficulty:null,isConnected:true,seat:0,result:null,role:null,vote:null};const room:Room={code:c,createdAt:Date.now(),startedAt:null,updatedAt:Date.now(),phase:"lobby",matchMode:mode(payload?.matchMode),players:[p],spectators:new Map(),speakerPlayerId:null,nominatedDeputyId:null,civicPolicies:0,controlPolicies:0,failedVotes:0,roundNumber:0,status:"Waiting for 5–10 players.",winner:null,deck:[],speakerHand:[],deputyHand:[],revealedVotes:null,actionSequence:0,actionLog:[]};rooms.set(c,room);emit(io,room);ack({ok:true,code:c,playerId:p.id,reconnectToken:p.reconnectToken,state:state(room,p.id,false)})});
 socket.on("hidden-dictator:join",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));if(!room)return ack({ok:false,reason:"Hidden Dictator room not found."});if(room.phase!=="lobby"||room.players.length>=10)return ack({ok:false,reason:"That room is full or already started."});const n=cleanName(payload?.playerName);if(!n)return ack({ok:false,reason:"Enter a player name."});const p:Player={id:socket.id,reconnectToken:token(),name:n,isHost:false,isAi:false,aiDifficulty:null,isConnected:true,seat:room.players.length,result:null,role:null,vote:null};room.players.push(p);emit(io,room);ack({ok:true,code:room.code,reconnectToken:p.reconnectToken,state:state(room,p.id,false)})});
 socket.on("hidden-dictator:reconnect",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const t=typeof payload?.reconnectToken==="string"?payload.reconnectToken.trim().toUpperCase():"";const p=room?.players.find(x=>x.reconnectToken===t&&!x.isAi);if(!room||!p)return ack({ok:false,reason:"Saved Hidden Dictator seat unavailable."});const oldId=p.id;p.id=socket.id;p.isConnected=true;if(room.speakerPlayerId===oldId)room.speakerPlayerId=p.id;if(room.nominatedDeputyId===oldId)room.nominatedDeputyId=p.id;if(room.revealedVotes)room.revealedVotes=room.revealedVotes.map(v=>v.playerId===oldId?{...v,playerId:p.id}:v);emit(io,room);ack({ok:true,reconnectToken:p.reconnectToken,state:state(room,p.id,false)})});
 socket.on("hidden-dictator:spectate",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));if(!room)return ack({ok:false,reason:"Room not found."});room.spectators.set(socket.id,cleanName(payload?.playerName)||"Spectator");emit(io,room);ack({ok:true,state:state(room,null,true)})});
 socket.on("hidden-dictator:add-ai",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const host=room?.players.find(p=>p.id===socket.id&&p.isHost);if(!room||!host)return ack({ok:false,reason:"Only the host can add AI."});const e=addAi(room,diff(payload?.difficulty));if(e)return ack({ok:false,reason:e});emit(io,room);ack({ok:true})});
 socket.on("hidden-dictator:remove-ai",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const host=room?.players.find(p=>p.id===socket.id&&p.isHost);if(!room||!host||room.phase!=="lobby")return ack({ok:false,reason:"Only the host can remove AI before play."});room.players=room.players.filter(p=>!(p.id===payload?.playerId&&p.isAi));room.players.forEach((p,i)=>p.seat=i);emit(io,room);ack({ok:true})});
 socket.on("hidden-dictator:start",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const host=room?.players.find(p=>p.id===socket.id&&p.isHost);if(!room||!host)return ack({ok:false,reason:"Only the host can start."});if(room.players.length<5)return ack({ok:false,reason:"Hidden Dictator needs at least five players. Add test AI if needed."});const roles=rolesFor(room.players.length);room.players.forEach((p,i)=>{p.role=roles[i];p.vote=null});room.deck=policyDeck();room.startedAt=Date.now();room.speakerPlayerId=null;log(room,{playerId:null,playerName:null,action:"table",detail:"Hidden Dictator started. Roles were assigned privately."});startRound(io,room);ack({ok:true})});
 socket.on("hidden-dictator:nominate",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const speaker=room?.players.find(p=>p.id===socket.id);const deputy=room?.players.find(p=>p.id===payload?.playerId);if(!room||!speaker||room.phase!=="nomination"||room.speakerPlayerId!==speaker.id||!deputy||deputy.id===speaker.id)return ack({ok:false,reason:"That nomination is not available."});room.nominatedDeputyId=deputy.id;room.phase="voting";room.status=`${speaker.name} nominated ${deputy.name}. Vote now.`;log(room,{playerId:speaker.id,playerName:speaker.name,action:"nominate",detail:room.status});emit(io,room);ack({ok:true})});
 socket.on("hidden-dictator:vote",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const p=room?.players.find(x=>x.id===socket.id);if(!room||!p||room.phase!=="voting"||p.vote)return ack({ok:false,reason:"You cannot vote now."});p.vote=payload?.vote==="approve"?"approve":"reject";if(room.players.every(x=>x.vote))resolveVotes(io,room);else emit(io,room);ack({ok:true})});
 socket.on("hidden-dictator:speaker-discard",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));if(!room||room.phase!=="speaker-policy"||room.speakerPlayerId!==socket.id)return ack({ok:false,reason:"Only the Speaker can discard now."});const i=Math.max(0,Math.min(2,Number(payload?.index)||0));room.deputyHand=room.speakerHand.filter((_,index)=>index!==i);room.speakerHand=[];room.phase="deputy-policy";room.status=`${room.players.find(p=>p.id===room.nominatedDeputyId)?.name??"Deputy"} is choosing the enacted policy.`;emit(io,room);ack({ok:true})});
 socket.on("hidden-dictator:deputy-enact",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));if(!room||room.phase!=="deputy-policy"||room.nominatedDeputyId!==socket.id)return ack({ok:false,reason:"Only the Deputy can enact now."});const i=Math.max(0,Math.min(1,Number(payload?.index)||0));const policy=room.deputyHand[i]??room.deputyHand[0];if(!policy)return ack({ok:false,reason:"No policy is available."});enact(io,room,policy);ack({ok:true})});
 socket.on("hidden-dictator:end-game",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const host=room?.players.find(p=>p.id===socket.id&&p.isHost);if(!room||!host)return ack({ok:false,reason:"Only the host can end the game."});room.phase="finished";room.status=`${host.name} ended Hidden Dictator.`;void finalizeSession("hidden-dictator",room.code,room.createdAt,"host-ended",archive(room),{winner:null,players:room.players.length,mode:room.matchMode,durationMs:Date.now()-room.createdAt});emit(io,room);ack({ok:true})});
 socket.on("hidden-dictator:forfeit",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const p=room?.players.find(x=>x.id===socket.id&&!x.isAi);if(!room||!p)return ack({ok:false,reason:"Seat not found."});log(room,{playerId:p.id,playerName:p.name,action:"forfeit",detail:`${p.name} left Hidden Dictator.`});room.players=room.players.filter(x=>x.id!==p.id);room.players.forEach((x,i)=>x.seat=i);if(p.isHost&&room.players[0])room.players[0].isHost=true;if(room.phase!=="lobby"&&room.players.length<5){room.phase="finished";room.status="Hidden Dictator ended because too few players remained.";}emit(io,room);ack({ok:true})});
 socket.on("hidden-dictator:leave",(payload:any,ack?:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const p=room?.players.find(x=>x.id===socket.id);if(p)p.isConnected=false;room?.spectators.delete(socket.id);if(room)emit(io,room);ack?.({ok:true})});socket.on("disconnect",()=>{for(const room of rooms.values()){const p=room.players.find(x=>x.id===socket.id);if(p){p.isConnected=false;emit(io,room)}if(room.spectators.delete(socket.id))emit(io,room)}});
}

export function getHiddenDictatorLiveRoomSummaries(): HalieusLiveRoomSummary[] {
  return [...rooms.values()]
    .filter((room) => room.phase !== "finished" && (room.players.some((player) => !player.isAi && player.isConnected) || room.spectators.size > 0))
    .map((room) => ({
      game: "hidden-dictator", gameTitle: "Hidden Dictator", code: room.code, phase: room.phase, matchMode: room.matchMode, started: room.phase !== "lobby",
      createdAt: room.createdAt, startedAt: room.startedAt, updatedAt: room.updatedAt, playerCount: room.players.length, maximumPlayers: 10,
      humanPlayers: room.players.filter((player) => !player.isAi && player.isConnected).map((player) => player.name), aiCount: room.players.filter((player) => player.isAi).length, spectatorCount: room.spectators.size,
      joinable: room.phase === "lobby" && room.players.length < 10, spectatable: true,
    }));
}
export function closeAllHiddenDictatorRooms(){const count=rooms.size;for(const t of timers.values())clearTimeout(t);timers.clear();rooms.clear();return count}
