import fs from 'node:fs';
import assert from 'node:assert/strict';
const read = (p) => fs.readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
const app = read('client/src/App.tsx');
const trade = read('client/src/games/mega-board/components/LiveTradeOverlay.tsx');
const tradeHandlers = read('server/src/games/mega-board/handlers/tradeHandlers.ts');
const whot = read('client/src/games/whot/WhotScreen.tsx');
const whotServer = read('server/src/games/whot/handlers.ts');
const poker = read('client/src/games/poker/PokerScreen.tsx');
const css = read('client/src/index.css');
assert.match(app, /game:trade-live-update/);
assert.match(app, /<LiveTradeOverlay/);
assert.match(trade, /Live deal negotiation/);
assert.match(tradeHandlers, /game:trade-live/);
assert.match(whotServer, /WhotMotionEvent/);
assert.match(whot, /WhotMotionLayer/);
assert.match(css, /whot-play-from-hand/);
assert.match(css, /lobby-shell-v2\[data-blitz="true"\]/);
assert.match(poker, /Deal first hand/);
assert.match(css, /poker-community-deal/);
console.log('RC 3.3.37 regression checks passed.');
