import assert from "node:assert/strict";
import { readFileSync, statSync } from "node:fs";
const read=(p)=>readFileSync(p,"utf8");
const pkg=JSON.parse(read("package.json"));
const version=read("VERSION").trim();
const home=read("client/src/platform/components/HomeScreen.tsx");
const portal=read("client/src/platform/accounts/AccountPortal.tsx");
const app=read("client/src/App.tsx");
const panel=read("client/src/platform/accounts/AccountPanel.tsx");
const accounts=read("server/src/platform/accounts.ts");
const server=read("server/src/index.ts");
const strategy=read("server/src/games/mega-board/ai/ai-strategy.ts");
const engine=read("server/src/games/mega-board/ai/ai-engine.ts");
const calibration=read("server/src/games/mega-board/ai/human-play-calibration.ts");
const css=read("client/src/index.css");
const brand=read("client/src/platform/components/GameBrandIcon.tsx");
const catalog=read("client/src/platform/games/catalog.ts");
assert.match(pkg.version, /^\d+\.\d+\.\d+(?:-[a-z0-9.-]+)?$/i);
assert.equal(version, pkg.version);
for (const label of ["Home","Games","Players","Join Game"]) assert.match(home,new RegExp(label));
assert.match(home,/accounts\/directory/); assert.match(home,/halieus-game-atmosphere/); assert.match(panel,/accounts\/me\/stats/);
assert.doesNotMatch(home,/scrollIntoView|scrollTo\(/);
assert.match(home,/--player-accent/); assert.match(home,/account\?\.playerColor/);
assert.doesNotMatch(portal,/One account for Mega Board|account342-game-row|Request access/);
assert.match(portal,/Sign in/); assert.match(portal,/Sign up/); assert.match(portal,/One-time play/);
assert.match(accounts,/\/admin\/rooms\/close-all/); assert.match(accounts,/\/admin\/rooms\/status/); assert.match(accounts,/\/accounts\/directory/); assert.match(accounts,/\/accounts\/me\/stats/);
assert.match(panel,/Close all rooms/); assert.match(panel,/rooms\.close-all/);
assert.match(server,/platform:all-rooms-closed/); assert.match(app,/socket\.on\("platform:all-rooms-closed"/);
assert.match(calibration,/Jordan: 21 auctions/); assert.match(calibration,/Elijah: winner/); assert.match(calibration,/Older retained human-involved archived games/);
assert.match(strategy,/humanStyleForSeat/); assert.match(strategy,/mobilityAggression/); assert.match(engine,/tryStrategicMortgage/); assert.match(engine,/HUMAN_STYLE_LEVERAGE/);
assert.match(css,/Halieus 3\.4\.2a/); assert.match(css,/prefers-reduced-motion/); assert.match(css,/halieus-game-atmosphere/);
assert.match(brand,/GAME_BY_ID\[game\]/);
for (const game of ["mega-board","poker","whot","ludo","blackjack"]) assert.match(catalog,new RegExp(`id: "${game}"`));
assert.ok(statSync("client/public/app-icon-512.png").size > 10000);
console.log("RC 3.4.2a shell/presence/admin/AI regression passed.");
