import { randomBytes } from "node:crypto";
import type { Server, Socket } from "socket.io";
import type { HalieusLiveRoomSummary } from "../../../../shared/platform/live-games.js";
import type { AyoActionLogEntry, AyoAiDifficulty, AyoMatchMode, AyoPlayer, AyoPublicState } from "../../../../shared/games/ayo/types.js";
import { finalizeSession, recordWorkingSession } from "../../platform/sessionArchive.js";

interface Player extends AyoPlayer { reconnectToken:string; }
interface Room { code:string; createdAt:number; startedAt:number|null; updatedAt:number; phase:"lobby"|"playing"|"finished"; matchMode:AyoMatchMode; players:Player[]; spectators:Map<string,string>; pits:number[]; currentPlayerId:string|null; winnerPlayerId:string|null; status:string; actionSequence:number; actionLog:AyoActionLogEntry[]; }
const rooms = new Map<string,Room>();
const aiTimers = new Map<string,NodeJS.Timeout>();
const AI_NAMES=["Adunni","Kola","Tayo","Sade","Kunle","Bisi","Femi","Yemi"];
function token(){return randomBytes(9).toString("base64url").slice(0,11).toUpperCase();}
function cleanCode(v:unknown){return typeof v==="string"?v.trim().toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6):"";}
function cleanName(v:unknown){return typeof v==="string"?v.trim().replace(/\s+/g," ").slice(0,24):"";}
function mode(v:unknown):AyoMatchMode{return v==="ranked"?"ranked":"casual";}
function difficulty(v:unknown):AyoAiDifficulty{return v==="easy"||v==="hard"?v:"normal";}
function pub(p:Player):AyoPlayer{const {reconnectToken:_r,...rest}=p;return rest;}
function state(room:Room,viewerId:string|null,isSpectator:boolean):AyoPublicState{return {game:"ayo",gameTitle:"Ayo",code:room.code,createdAt:room.createdAt,startedAt:room.startedAt,updatedAt:room.updatedAt,phase:room.phase,matchMode:room.matchMode,players:room.players.map(pub),spectatorCount:room.spectators.size,viewerPlayerId:viewerId,isSpectator,pits:[...room.pits],currentPlayerId:room.currentPlayerId,winnerPlayerId:room.winnerPlayerId,status:room.status,actionLog:room.actionLog.slice(-180)};}
function log(room:Room,entry:Omit<AyoActionLogEntry,"sequence"|"at">){room.actionSequence++;room.actionLog.push({...entry,sequence:room.actionSequence,at:Date.now()});if(room.actionLog.length>180)room.actionLog.splice(0,room.actionLog.length-180);}
function archive(room:Room){return {...room,spectators:[...room.spectators.entries()]};}
function emit(io:Server,room:Room){room.updatedAt=Date.now();recordWorkingSession("ayo",room.code,room.createdAt,archive(room));for(const p of room.players)if(!p.isAi&&p.isConnected)io.to(p.id).emit("ayo:state",state(room,p.id,false));for(const id of room.spectators.keys())io.to(id).emit("ayo:state",state(room,null,true));scheduleAi(io,room);}
function side(seat:number){return seat===0?[0,1,2,3,4,5]:[6,7,8,9,10,11];}
function owns(seat:number,pit:number){return seat===0?pit>=0&&pit<6:pit>=6&&pit<12;}
function opposite(pit:number){return 11-pit;}
function simulate(source:number[],seat:number,start:number){const pits=[...source];if(!owns(seat,start)||pits[start]<=0)return null;const original=start;let hand=pits[start];pits[start]=0;let cursor=start;let guard=0;while(hand>0&&guard++<500){cursor=(cursor+1)%12;if(cursor===original)continue;pits[cursor]++;hand--;if(hand===0){if(pits[cursor]>1){hand=pits[cursor];pits[cursor]=0;continue;}break;}}if(guard>=500)return null;let captured=0;if(owns(seat,cursor)&&pits[cursor]===1){const opp=opposite(cursor);if(pits[opp]>0){captured=pits[opp];pits[opp]=0;pits[cursor]=0;}}
return {pits,last:cursor,captured};}
function hasSeeds(room:Room,seat:number){return side(seat).some((pit)=>room.pits[pit]>0);}
function moveFeeds(room:Room,seat:number,pit:number){const result=simulate(room.pits,seat,pit);if(!result)return false;return side(seat===0?1:0).some((p)=>result.pits[p]>0);}
function legalPits(room:Room,seat:number){const candidates=side(seat).filter((pit)=>room.pits[pit]>0);const opponent=seat===0?1:0;if(hasSeeds(room,opponent))return candidates;const feeding=candidates.filter((pit)=>moveFeeds(room,seat,pit));return feeding.length?feeding:candidates;}
function other(room:Room,p:Player){return room.players.find((x)=>x.id!==p.id)??null;}
function finish(io:Server,room:Room,winner:Player|null,reason:string){if(room.phase==="finished")return;room.phase="finished";room.currentPlayerId=null;room.winnerPlayerId=winner?.id??null;room.status=reason;for(const p of room.players)p.result=winner?p.id===winner.id?"Winner":"Runner-up":"Draw";log(room,{playerId:winner?.id??null,playerName:winner?.name??null,action:"finish",pit:null,detail:reason});void finalizeSession("ayo",room.code,room.createdAt,"completed",archive(room),{winner:winner?.name??null,players:room.players.length,mode:room.matchMode,durationMs:Date.now()-room.createdAt});emit(io,room);io.emit("platform:game-finished",{id:`ayo-${room.code}-${room.actionSequence}`,game:"ayo",gameTitle:"Ayo",code:room.code,status:"game-finished",winner:winner?.name??null,message:reason,at:room.updatedAt});}
function maybeFinish(io:Server,room:Room){const current=room.players.find((p)=>p.id===room.currentPlayerId);if(!current)return;const legal=legalPits(room,current.seat);if(legal.length>0&&hasSeeds(room,current.seat))return;const opponent=other(room,current);if(!opponent)return;const remaining=room.pits.reduce((a,b)=>a+b,0);opponent.captured+=remaining;room.pits.fill(0);const winner=room.players[0].captured===room.players[1].captured?null:room.players[0].captured>room.players[1].captured?room.players[0]:room.players[1];finish(io,room,winner,winner?`${winner.name} wins Ayo ${winner.captured}-${other(room,winner)?.captured??0}.`:`Ayo ends level ${room.players[0].captured}-${room.players[1].captured}.`);}
function play(io:Server,room:Room,p:Player,pit:number){if(room.phase!=="playing")return "Ayo is not currently in play.";if(room.currentPlayerId!==p.id)return "It is not your turn.";if(!Number.isInteger(pit)||!owns(p.seat,pit))return "Choose one of your six houses.";const legal=legalPits(room,p.seat);if(!legal.includes(pit))return !hasSeeds(room,p.seat)?"You have no legal house to sow.":"That move must feed the opponent.";const before=room.pits[pit];const result=simulate(room.pits,p.seat,pit);if(!result)return "That Ayo move is unavailable.";room.pits=result.pits;p.captured+=result.captured;log(room,{playerId:p.id,playerName:p.name,action:"sow",pit,detail:`${p.name} sowed ${before} seed${before===1?"":"s"} from house ${p.seat===0?pit+1:pit-5}.`});if(result.captured)log(room,{playerId:p.id,playerName:p.name,action:"capture",pit:result.last,detail:`${p.name} captured ${result.captured} seed${result.captured===1?"":"s"}.`});const opponent=other(room,p);room.currentPlayerId=opponent?.id??null;room.status=opponent?`${opponent.name} to sow.`:"Ayo continues.";maybeFinish(io,room);if(room.phase!=="finished")emit(io,room);return null;}
function choose(room:Room,p:Player){const legal=legalPits(room,p.seat);if(!legal.length)return -1;if(p.aiDifficulty==="easy")return legal[Math.floor(Math.random()*legal.length)];const scored=legal.map((pit)=>({pit,result:simulate(room.pits,p.seat,pit)})).sort((a,b)=>(b.result?.captured??0)-(a.result?.captured??0));if(p.aiDifficulty==="hard"){const safe=scored.find((item)=>{if(!item.result)return false;const opponentSeat=p.seat===0?1:0;return side(opponentSeat).reduce((sum,i)=>sum+item.result!.pits[i],0)>0;});if(safe)return safe.pit;}return scored[0]?.pit??legal[0];}
function scheduleAi(io:Server,room:Room){const old=aiTimers.get(room.code);if(old)clearTimeout(old);if(room.phase!=="playing")return;const p=room.players.find((x)=>x.id===room.currentPlayerId);if(!p?.isAi)return;aiTimers.set(room.code,setTimeout(()=>{if(room.phase!=="playing"||room.currentPlayerId!==p.id)return;const pit=choose(room,p);if(pit>=0)play(io,room,p,pit);else maybeFinish(io,room);},800));}
export function getAyoRoomCount(){return [...rooms.values()].filter((room)=>room.phase!=="finished"&&(room.players.some((p)=>!p.isAi&&p.isConnected)||room.spectators.size>0)).length;}
export function getAyoChatIdentity(c:string,socketId:string){const room=rooms.get(cleanCode(c));if(!room)return null;const p=room.players.find((x)=>x.id===socketId&&x.isConnected);if(p)return{name:p.name,role:"player" as const};const s=room.spectators.get(socketId);return s?{name:s,role:"spectator" as const}:null;}
export function registerAyoHandlers(io:Server,socket:Socket){
 socket.on("ayo:create",(payload:any,ack:(r:any)=>void)=>{const c=cleanCode(payload?.code)||token().slice(0,6);if(rooms.has(c)&&rooms.get(c)?.phase!=="finished")return ack({ok:false,reason:"That Ayo room already exists."});const n=cleanName(payload?.playerName);if(!n)return ack({ok:false,reason:"Enter a player name."});const p:Player={id:socket.id,reconnectToken:token(),name:n,isHost:true,isAi:false,aiDifficulty:null,isConnected:true,seat:0,captured:0,result:null};const room:Room={code:c,createdAt:Date.now(),startedAt:null,updatedAt:Date.now(),phase:"lobby",matchMode:mode(payload?.matchMode),players:[p],spectators:new Map(),pits:Array(12).fill(4),currentPlayerId:null,winnerPlayerId:null,status:"Waiting for one more player.",actionSequence:0,actionLog:[]};rooms.set(c,room);emit(io,room);ack({ok:true,code:c,playerId:p.id,reconnectToken:p.reconnectToken,state:state(room,p.id,false)});});
 socket.on("ayo:join",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));if(!room)return ack({ok:false,reason:"Ayo room not found."});if(room.phase!=="lobby"||room.players.length>=2)return ack({ok:false,reason:"That Ayo board is full or already started."});const n=cleanName(payload?.playerName);if(!n)return ack({ok:false,reason:"Enter a player name."});const p:Player={id:socket.id,reconnectToken:token(),name:n,isHost:false,isAi:false,aiDifficulty:null,isConnected:true,seat:1,captured:0,result:null};room.players.push(p);emit(io,room);ack({ok:true,code:room.code,playerId:p.id,reconnectToken:p.reconnectToken,state:state(room,p.id,false)});});
 socket.on("ayo:reconnect",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const t=typeof payload?.reconnectToken==="string"?payload.reconnectToken.trim().toUpperCase():"";const p=room?.players.find((x)=>x.reconnectToken===t&&!x.isAi);if(!room||!p)return ack({ok:false,reason:"That saved Ayo seat is not available."});const old=p.id;p.id=socket.id;p.isConnected=true;if(room.currentPlayerId===old)room.currentPlayerId=p.id;if(room.winnerPlayerId===old)room.winnerPlayerId=p.id;emit(io,room);ack({ok:true,code:room.code,playerId:p.id,reconnectToken:p.reconnectToken,state:state(room,p.id,false)});});
 socket.on("ayo:spectate",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));if(!room)return ack({ok:false,reason:"Ayo room not found."});room.spectators.set(socket.id,cleanName(payload?.playerName)||"Spectator");emit(io,room);ack({ok:true,state:state(room,null,true)});});
 socket.on("ayo:add-ai",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const host=room?.players.find((x)=>x.id===socket.id&&x.isHost);if(!room||!host)return ack({ok:false,reason:"Only the host can add AI."});if(room.phase!=="lobby"||room.players.length>=2)return ack({ok:false,reason:"Ayo has two seats."});const used=new Set(room.players.map((p)=>p.name));const n=AI_NAMES.find((x)=>!used.has(x))??"Ayo AI";room.players.push({id:`ayo-ai-${token()}`,reconnectToken:"",name:n,isHost:false,isAi:true,aiDifficulty:difficulty(payload?.difficulty),isConnected:true,seat:1,captured:0,result:null});emit(io,room);ack({ok:true});});
 socket.on("ayo:remove-ai",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const host=room?.players.find((x)=>x.id===socket.id&&x.isHost);if(!room||!host||room.phase!=="lobby")return ack({ok:false,reason:"Only the host can remove AI before play."});room.players=room.players.filter((x)=>!(x.id===payload?.playerId&&x.isAi));emit(io,room);ack({ok:true});});
 socket.on("ayo:start",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const host=room?.players.find((x)=>x.id===socket.id&&x.isHost);if(!room||!host)return ack({ok:false,reason:"Only the host can start Ayo."});if(room.players.length!==2)return ack({ok:false,reason:"Ayo needs exactly two players."});room.pits=Array(12).fill(4);room.players.forEach((p)=>{p.captured=0;p.result=null});room.phase="playing";room.startedAt=room.startedAt??Date.now();room.currentPlayerId=room.players[0].id;room.winnerPlayerId=null;room.status=`${room.players[0].name} to sow.`;log(room,{playerId:null,playerName:null,action:"start",pit:null,detail:"Traditional Yoruba Ayo started with four seeds in each house."});emit(io,room);ack({ok:true});});
 socket.on("ayo:sow",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const p=room?.players.find((x)=>x.id===socket.id);if(!room||!p)return ack({ok:false,reason:"Ayo seat not found."});const reason=play(io,room,p,Number(payload?.pit));if(reason)return ack({ok:false,reason});ack({ok:true});});
 socket.on("ayo:forfeit",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const p=room?.players.find((x)=>x.id===socket.id&&!x.isAi);if(!room||!p)return ack({ok:false,reason:"Ayo seat not found."});const winner=other(room,p);finish(io,room,winner,winner?`${p.name} forfeited. ${winner.name} wins Ayo.`:`${p.name} forfeited.`);ack({ok:true});});
 socket.on("ayo:end-game",(payload:any,ack:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const host=room?.players.find((x)=>x.id===socket.id&&x.isHost);if(!room||!host)return ack({ok:false,reason:"Only the host can end Ayo."});finish(io,room,null,`${host.name} ended the Ayo game.`);ack({ok:true});});
 socket.on("ayo:leave",(payload:any,ack?:(r:any)=>void)=>{const room=rooms.get(cleanCode(payload?.code));const p=room?.players.find((x)=>x.id===socket.id);if(p)p.isConnected=false;room?.spectators.delete(socket.id);if(room)emit(io,room);ack?.({ok:true});});
 socket.on("disconnect",()=>{for(const room of rooms.values()){const p=room.players.find((x)=>x.id===socket.id);if(p){p.isConnected=false;emit(io,room);}if(room.spectators.delete(socket.id))emit(io,room);}});
}
export function getAyoLiveRoomSummaries():HalieusLiveRoomSummary[]{return [...rooms.values()].filter((room)=>room.phase!=="finished"&&(room.players.some((p)=>!p.isAi&&p.isConnected)||room.spectators.size>0)).map((room)=>({game:"ayo",gameTitle:"Ayo",code:room.code,phase:room.phase,matchMode:room.matchMode,started:room.phase!=="lobby",createdAt:room.createdAt,startedAt:room.startedAt,updatedAt:room.updatedAt,playerCount:room.players.length,maximumPlayers:2,humanPlayers:room.players.filter((p)=>!p.isAi&&p.isConnected).map((p)=>p.name),aiCount:room.players.filter((p)=>p.isAi).length,spectatorCount:room.spectators.size,joinable:room.phase==="lobby"&&room.players.length<2,spectatable:true}));}
export function closeAllAyoRooms(){const count=getAyoRoomCount();for(const timer of aiTimers.values())clearTimeout(timer);aiTimers.clear();rooms.clear();return count;}
