// Generated by scripts/release-integrity.mjs. Do not edit by hand.
export const RELEASE_FINGERPRINT = "hgr-4.1.1-fca144bf7ce1fd21";
export const RELEASE_SOURCE_HASH = "fca144bf7ce1fd21cbcf0e514ee5760744745141cfdd598094b75a895526c0eb";
