// Generated by scripts/release-integrity.mjs. Do not edit by hand.
export const RELEASE_FINGERPRINT = "hgr-4.1.0-966ec817257fea44";
export const RELEASE_SOURCE_HASH = "966ec817257fea449ff7f67aacb114fd60aa5da76b63a0b514fdd19ef43e4b83";
