// Generated by scripts/release-integrity.mjs. Do not edit by hand.
export const RELEASE_FINGERPRINT = "hgr-4.1.0-aaff2329612ae368";
export const RELEASE_SOURCE_HASH = "aaff2329612ae3689c651059e239402a12caceae976164c1ac4e9bf2276e173c";
