import { useMemo, useState, type ReactNode } from "react";
import type { AyoAiDifficulty, AyoPublicState } from "../../../../shared/games/ayo/types";
import { GameChrome } from "../../platform/components/GameChrome";
import { GameBrandIcon } from "../../platform/components/GameBrandIcon";
import { DisplaySettingsPanel } from "../../platform/components/DisplaySettingsPanel";
import { InviteLobbyPanel } from "../../platform/components/InviteLobbyPanel";
import { ConfirmDialog } from "../../platform/components/ConfirmDialog";
import { GameResultsScreen } from "../../platform/components/GameResultsScreen";

const ACCENT="#b87938";
interface ThemeLike{pageBackground:string;cardBackground:string;secondaryBackground:string;inputBackground:string;text:string;mutedText:string;border:string;}
interface Props{state:AyoPublicState;connectionStatus:string;message:string;darkMode:boolean;theme:ThemeLike;soundEnabled:boolean;onToggleFullscreen:()=>void;onToggleDarkMode:()=>void;onToggleSound:()=>void;onStart:()=>void;onAddAi:(d:AyoAiDifficulty)=>void;onRemoveAi:(id:string)=>void;onSow:(pit:number)=>void;onEndGame:()=>void;onForfeit:()=>void;onLeave:()=>void;roomActivity?:ReactNode;}
export function AyoScreen({state,connectionStatus,message,darkMode,theme,soundEnabled,onToggleFullscreen,onToggleDarkMode,onToggleSound,onStart,onAddAi,onRemoveAi,onSow,onEndGame,onForfeit,onLeave,roomActivity}:Props){
 const [menuOpen,setMenuOpen]=useState(false),[inviteOpen,setInviteOpen]=useState(false),[aiDifficulty,setAiDifficulty]=useState<AyoAiDifficulty>("normal"),[confirm,setConfirm]=useState<"forfeit"|"end"|null>(null);
 const viewer=state.players.find(p=>p.id===state.viewerPlayerId),isHost=Boolean(viewer?.isHost),canAct=Boolean(viewer&&!state.isSpectator&&state.phase==="playing"&&state.currentPlayerId===viewer.id);
 const top=useMemo(()=>[11,10,9,8,7,6],[]),bottom=useMemo(()=>[0,1,2,3,4,5],[]);
 const rows=state.players.slice().sort((a,b)=>b.captured-a.captured).map((p,i)=>({id:p.id,rank:i+1,name:p.name,detail:`${p.captured} captured`,winner:p.id===state.winnerPlayerId,status:p.result??"Player"}));
 return <main className="ayo-page page-enter" style={{background:theme.pageBackground,color:theme.text,["--game-accent" as string]:ACCENT}}>
  <GameChrome accent={ACCENT} onBackToGameRoom={onLeave} onOpenMenu={()=>setMenuOpen(true)}/>
  <header className="card-game-header card-game-header-polished"><div className="card-game-brand-lockup"><GameBrandIcon game="ayo"/><div><p>YORUBA TABLE</p><h1>Ayo</h1></div></div><div className="card-game-meta"><span>Room {state.code}</span><span>Traditional rules</span><span className={connectionStatus==="Connected"?"is-online":""}>{connectionStatus}</span></div></header>
  {state.phase==="lobby"?<section className="card-game-lobby ayo-lobby"><article className="card-game-lobby-card"><p className="modal-eyebrow">TRADITIONAL YORUBA AYO</p><h2>Sow the board. Read the rhythm.</h2><p className="card-game-intro-copy">Two players, twelve houses and forty-eight seeds. Relay sowing and captures are resolved by the server so every player sees the same board.</p>{isHost&&<div className="card-game-host-actions"><label className="card-game-ai-control">AI player<select value={aiDifficulty} onChange={e=>setAiDifficulty(e.target.value as AyoAiDifficulty)}><option value="easy">Easy</option><option value="normal">Normal</option><option value="hard">Hard</option></select></label><button type="button" className="button-outline" disabled={state.players.length>=2} onClick={()=>onAddAi(aiDifficulty)}>Add AI</button><button type="button" className="button-primary" disabled={state.players.length!==2} onClick={onStart}>Start Ayo</button></div>}<button type="button" className="button-muted" onClick={()=>setInviteOpen(true)}>Invite player</button></article><section className="card-game-roster"><header><div><p className="modal-eyebrow">SEATS</p><h2>Players</h2></div><span>{state.players.length}/2</span></header>{state.players.map(p=><article key={p.id} className="card-game-player-row"><span className="ayo-avatar">{p.name.slice(0,1)}</span><div><strong>{p.name}</strong><small>{p.isHost?"Host":p.isAi?`${p.aiDifficulty} AI`:"Player"}</small></div>{isHost&&p.isAi&&<button type="button" onClick={()=>onRemoveAi(p.id)}>×</button>}</article>)}</section></section>
  :state.phase==="finished"?<GameResultsScreen accent={ACCENT} gameTitle="Ayo" roomCode={state.code} headline={state.winnerPlayerId?`${state.players.find(p=>p.id===state.winnerPlayerId)?.name??"Winner"} wins Ayo`:"Ayo finished"} subtitle={state.status} rows={rows} stats={[{label:"Seeds",value:"48"},{label:"Houses",value:"12"},{label:"Mode",value:state.matchMode}]} onDownloadReport={()=>{const text=[`HALIEUS AYO · ${state.code}`,state.status,...rows.map(row=>`${row.rank}. ${row.name} · ${row.detail}`)].join("\n");const url=URL.createObjectURL(new Blob([text],{type:"text/plain"}));const a=document.createElement("a");a.href=url;a.download=`ayo-${state.code}-report.txt`;a.click();URL.revokeObjectURL(url);}} onBackToGameRoom={onLeave} onPlayAgain={isHost?onStart:undefined}/>
  :<section className="ayo-live-shell"><div className="ayo-stage"><header className="ayo-scorebar">{state.players.map(p=><article key={p.id} className={state.currentPlayerId===p.id?"is-turn":""}><span>{p.name}</span><strong>{p.captured}</strong><small>captured</small></article>)}</header><div className="ayo-board-wrap"><div className="ayo-board" role="grid" aria-label="Traditional Ayo board"><div className="ayo-row ayo-row-top">{top.map(pit=><button type="button" key={pit} disabled={!canAct||viewer?.seat!==1||state.pits[pit]===0} onClick={()=>onSow(pit)} aria-label={`House ${pit-5}, ${state.pits[pit]} seeds`}><span>{Array.from({length:Math.min(state.pits[pit],12)},(_,i)=><i key={i}/>)}</span><b>{state.pits[pit]}</b></button>)}</div><div className="ayo-board-centre"><span>{state.status}</span></div><div className="ayo-row ayo-row-bottom">{bottom.map(pit=><button type="button" key={pit} disabled={!canAct||viewer?.seat!==0||state.pits[pit]===0} onClick={()=>onSow(pit)} aria-label={`House ${pit+1}, ${state.pits[pit]} seeds`}><span>{Array.from({length:Math.min(state.pits[pit],12)},(_,i)=><i key={i}/>)}</span><b>{state.pits[pit]}</b></button>)}</div></div></div>{message&&<p className="status-toast">{message}</p>}</div>{roomActivity&&<aside className="ayo-room-stack">{roomActivity}</aside>}</section>}
  {inviteOpen&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setInviteOpen(false)}><section className="card-game-invite-modal"><button type="button" className="icon-button invite-modal-close" onClick={()=>setInviteOpen(false)}>×</button><InviteLobbyPanel roomCode={state.code} darkMode={darkMode} gameTitle="Ayo" invitePathPrefix="/ayo" accent={ACCENT} theme={theme}/></section></div>}
  {menuOpen&&<div className="modal-backdrop game-menu-top-layer" onMouseDown={e=>e.target===e.currentTarget&&setMenuOpen(false)}><section className="game-menu-modal card-game-menu-modal"><header className="modal-heading-row"><div><p className="modal-eyebrow">Ayo · Room {state.code}</p><h2>Game menu</h2></div><button className="icon-button" onClick={()=>setMenuOpen(false)}>×</button></header><DisplaySettingsPanel darkMode={darkMode} soundEnabled={soundEnabled} onToggleDarkMode={onToggleDarkMode} onToggleSound={onToggleSound} onToggleFullscreen={onToggleFullscreen}/><button className="menu-action" onClick={onLeave}>← Back to Game Room</button>{viewer&&!state.isSpectator&&<button className="menu-action menu-action-danger" onClick={()=>{setMenuOpen(false);setConfirm("forfeit")}}>⚑ Forfeit</button>}{isHost&&<button className="menu-action menu-action-danger" onClick={()=>{setMenuOpen(false);setConfirm("end")}}>■ End game</button>}</section></div>}
  <ConfirmDialog open={confirm!==null} title={confirm==="end"?"End Ayo?":"Forfeit Ayo?"} message={confirm==="end"?"This ends and archives the Ayo room for everyone.":"Your opponent will win this game."} confirmLabel={confirm==="end"?"End game":"Forfeit"} destructive onCancel={()=>setConfirm(null)} onConfirm={()=>{const a=confirm;setConfirm(null);a==="end"?onEndGame():onForfeit();}}/>
 </main>;
}
